// HSK 3.0 Vocabulary organized by level
const HSK = {
  1: [
    {"h":"爱","p":"ài","e":"to love"},
    {"h":"八","p":"bā","e":"eight"},
    {"h":"爸爸","p":"bàba","e":"dad"},
    {"h":"吧","p":"ba","e":"particle indicating suggestion, confirmation, or hesitation"},
    {"h":"白天","p":"báitiān","e":"daytime"},
    {"h":"百","p":"bǎi","e":"hundred"},
    {"h":"半","p":"bàn","e":"half"},
    {"h":"包子","p":"bāozi","e":"steamed stuffed bun"},
    {"h":"杯子","p":"bēizi","e":"cup, glass"},
    {"h":"本","p":"běn","e":"measure word for books"},
    {"h":"边","p":"biān","e":"side"},
    {"h":"病","p":"bìng","e":"illness, disease"},
    {"h":"不","p":"bù","e":"not, no"},
    {"h":"不客气","p":"bú kèqi","e":"you're welcome"},
    {"h":"不要","p":"búyào","e":"don't, not want"},
    {"h":"菜","p":"cài","e":"vegetable, dish"},
    {"h":"茶","p":"chá","e":"tea"},
    {"h":"唱","p":"chàng","e":"to sing"},
    {"h":"超市","p":"chāoshì","e":"supermarket"},
    {"h":"车","p":"chē","e":"vehicle, car"},
    {"h":"吃","p":"chī","e":"to eat"},
    {"h":"出租车","p":"chūzūchē","e":"taxi"},
    {"h":"穿","p":"chuān","e":"to wear"},
    {"h":"打电话","p":"dǎ diànhuà","e":"to make a phone call"},
    {"h":"大","p":"dà","e":"big"},
    {"h":"大家","p":"dàjiā","e":"everyone"},
    {"h":"大学","p":"dàxué","e":"university"},
    {"h":"大学生","p":"dàxuéshēng","e":"university student"},
    {"h":"到","p":"dào","e":"to arrive"},
    {"h":"的","p":"de","e":"possessive or modifying particle"},
    {"h":"第","p":"dì","e":"prefix for ordinal numbers"},
    {"h":"弟弟","p":"dìdi","e":"younger brother"},
    {"h":"点","p":"diǎn","e":"measure word for small round things"},
    {"h":"店","p":"diàn","e":"shop, store"},
    {"h":"电话","p":"diànhuà","e":"telephone, phone call"},
    {"h":"电脑","p":"diànnǎo","e":"computer"},
    {"h":"电视","p":"diànshì","e":"television"},
    {"h":"电影","p":"diànyǐng","e":"movie, film"},
    {"h":"电影院","p":"diànyǐngyuàn","e":"cinema"},
    {"h":"东西","p":"dōngxi","e":"thing, object"},
    {"h":"都","p":"dōu","e":"all, both"},
    {"h":"读","p":"dú","e":"to read"},
    {"h":"读书","p":"dúshū","e":"to read a book"},
    {"h":"对","p":"duì","e":"correct, right"},
    {"h":"对不起","p":"duìbuqǐ","e":"sorry"},
    {"h":"多","p":"duō","e":"many, much"},
    {"h":"多少","p":"duōshao","e":"how many, how much"},
    {"h":"儿子","p":"érzi","e":"son"},
    {"h":"二","p":"èr","e":"two"},
    {"h":"饭","p":"fàn","e":"cooked rice, meal"},
    {"h":"饭店","p":"fàndiàn","e":"restaurant"},
    {"h":"房间","p":"fángjiān","e":"room"},
    {"h":"非常","p":"fēicháng","e":"very, extremely"},
    {"h":"飞机","p":"fēijī","e":"airplane"},
    {"h":"分","p":"fēn","e":"minute"},
    {"h":"分钟","p":"fēnzhōng","e":"minute"},
    {"h":"高兴","p":"gāoxìng","e":"happy, glad"},
    {"h":"歌","p":"gē","e":"song"},
    {"h":"哥哥","p":"gēge","e":"older brother"},
    {"h":"个","p":"gè","e":"measure word for general objects"},
    {"h":"给","p":"gěi","e":"to give"},
    {"h":"公司","p":"gōngsī","e":"company"},
    {"h":"工作","p":"gōngzuò","e":"work"},
    {"h":"狗","p":"gǒu","e":"dog"},
    {"h":"贵","p":"guì","e":"expensive"},
    {"h":"国","p":"guó","e":"country"},
    {"h":"还","p":"hái","e":"still, also"},
    {"h":"孩子","p":"háizi","e":"child"},
    {"h":"汉语","p":"Hànyǔ","e":"Chinese language"},
    {"h":"汉字","p":"Hànzì","e":"Chinese character"},
    {"h":"好","p":"hǎo","e":"good"},
    {"h":"好吃","p":"hǎochī","e":"delicious, tasty"},
    {"h":"好看","p":"hǎokàn","e":"good-looking"},
    {"h":"好听","p":"hǎotīng","e":"pleasant to listen to"},
    {"h":"好玩儿","p":"hǎowánr","e":"fun, amusing"},
    {"h":"号","p":"hào","e":"number"},
    {"h":"喝","p":"hē","e":"to drink"},
    {"h":"和","p":"hé","e":"and, with"},
    {"h":"很","p":"hěn","e":"very"},
    {"h":"后","p":"hòu","e":"behind, later"},
    {"h":"回","p":"huí","e":"to return"},
    {"h":"会","p":"huì","e":"can, to be able to"},
    {"h":"火车","p":"huǒchē","e":"train"},
    {"h":"鸡蛋","p":"jīdàn","e":"egg"},
    {"h":"几","p":"jǐ","e":"how many, a few"},
    {"h":"家","p":"jiā","e":"home, family"},
    {"h":"家人","p":"jiārén","e":"family member"},
    {"h":"见","p":"jiàn","e":"to see"},
    {"h":"件","p":"jiàn","e":"measure word for items"},
    {"h":"饺子","p":"jiǎozi","e":"dumpling"},
    {"h":"叫","p":"jiào","e":"to be called, to call"},
    {"h":"姐姐","p":"jiějie","e":"older sister"},
    {"h":"今年","p":"jīnnián","e":"this year"},
    {"h":"今天","p":"jīntiān","e":"today"},
    {"h":"九","p":"jiǔ","e":"nine"},
    {"h":"觉得","p":"juéde","e":"to feel, to think"},
    {"h":"开","p":"kāi","e":"to open"},
    {"h":"开车","p":"kāichē","e":"to drive"},
    {"h":"看","p":"kàn","e":"to see, to look"},
    {"h":"看病","p":"kànbìng","e":"to see a doctor"},
    {"h":"看见","p":"kànjiàn","e":"to see"},
    {"h":"可以","p":"kěyǐ","e":"can, may"},
    {"h":"课","p":"kè","e":"class, lesson"},
    {"h":"口","p":"kǒu","e":"mouth"},
    {"h":"块","p":"kuài","e":"measure word for pieces, chunks, money"},
    {"h":"来","p":"lái","e":"to come"},
    {"h":"老师","p":"lǎoshī","e":"teacher"},
    {"h":"了","p":"le","e":"particle indicating completed action"},
    {"h":"冷","p":"lěng","e":"cold"},
    {"h":"里","p":"lǐ","e":"inside, in, mile"},
    {"h":"两","p":"liǎng","e":"two"},
    {"h":"零","p":"líng","e":"zero"},
    {"h":"六","p":"liù","e":"six"},
    {"h":"妈妈","p":"māma","e":"mom"},
    {"h":"吗","p":"ma","e":"question particle"},
    {"h":"买","p":"mǎi","e":"to buy"},
    {"h":"卖","p":"mài","e":"to sell"},
    {"h":"忙","p":"máng","e":"busy"},
    {"h":"猫","p":"māo","e":"cat"},
    {"h":"没关系","p":"méi guānxi","e":"never mind, it's okay"},
    {"h":"没事","p":"méishì","e":"to have nothing to do"},
    {"h":"没有","p":"méiyǒu","e":"to not have"},
    {"h":"妹妹","p":"mèimei","e":"younger sister"},
    {"h":"们","p":"men","e":"plural suffix"},
    {"h":"米饭","p":"mǐfàn","e":"cooked rice"},
    {"h":"面包","p":"miànbāo","e":"bread"},
    {"h":"面条儿","p":"miàntiáor","e":"noodles"},
    {"h":"明年","p":"míngnián","e":"next year"},
    {"h":"明天","p":"míngtiān","e":"tomorrow"},
    {"h":"名字","p":"míngzi","e":"name"},
    {"h":"哪","p":"nǎ","e":"which"},
    {"h":"哪个","p":"nǎge","e":"which one"},
    {"h":"哪里","p":"nǎlǐ","e":"where"},
    {"h":"哪儿","p":"nǎr","e":"where"},
    {"h":"哪些","p":"nǎxiē","e":"which ones"},
    {"h":"那","p":"nà","e":"that"},
    {"h":"那边","p":"nàbiān","e":"over there"},
    {"h":"那个","p":"nàge","e":"that one"},
    {"h":"那里","p":"nàlǐ","e":"there"},
    {"h":"那儿","p":"nàr","e":"there"},
    {"h":"那些","p":"nàxiē","e":"those"},
    {"h":"男","p":"nán","e":"male"},
    {"h":"男朋友","p":"nánpéngyou","e":"boyfriend"},
    {"h":"呢","p":"ne","e":"question or continuation particle"},
    {"h":"能","p":"néng","e":"can, be able to"},
    {"h":"你","p":"nǐ","e":"you"},
    {"h":"你好","p":"nǐ hǎo","e":"hello"},
    {"h":"你们","p":"nǐmen","e":"you plural"},
    {"h":"年","p":"nián","e":"year"},
    {"h":"您","p":"nín","e":"you"},
    {"h":"牛奶","p":"niúnǎi","e":"milk"},
    {"h":"女","p":"nǚ","e":"female"},
    {"h":"女儿","p":"nǚ'ér","e":"daughter"},
    {"h":"女朋友","p":"nǚpéngyou","e":"girlfriend"},
    {"h":"女士","p":"nǚshì","e":"lady, Ms."},
    {"h":"朋友","p":"péngyou","e":"friend"},
    {"h":"便宜","p":"piányi","e":"cheap"},
    {"h":"漂亮","p":"piàoliang","e":"beautiful"},
    {"h":"苹果","p":"píngguǒ","e":"apple"},
    {"h":"七","p":"qī","e":"seven"},
    {"h":"起床","p":"qǐchuáng","e":"to get up"},
    {"h":"千","p":"qiān","e":"thousand"},
    {"h":"前","p":"qián","e":"front, before"},
    {"h":"钱","p":"qián","e":"money"},
    {"h":"请","p":"qǐng","e":"please"},
    {"h":"请问","p":"qǐngwèn","e":"may I ask"},
    {"h":"去","p":"qù","e":"to go"},
    {"h":"去年","p":"qùnián","e":"last year"},
    {"h":"热","p":"rè","e":"hot"},
    {"h":"人","p":"rén","e":"person"},
    {"h":"认识","p":"rènshi","e":"to know, to recognize"},
    {"h":"日","p":"rì","e":"measure word for days"},
    {"h":"三","p":"sān","e":"three"},
    {"h":"商店","p":"shāngdiàn","e":"store, shop"},
    {"h":"上","p":"shàng","e":"up, above"},
    {"h":"上班","p":"shàngbān","e":"to go to work"},
    {"h":"上课","p":"shàngkè","e":"to attend class"},
    {"h":"上午","p":"shàngwǔ","e":"morning"},
    {"h":"上学","p":"shàngxué","e":"to go to school"},
    {"h":"少","p":"shǎo","e":"few, little"},
    {"h":"谁","p":"shéi","e":"who"},
    {"h":"什么","p":"shénme","e":"what"},
    {"h":"生病","p":"shēngbìng","e":"to get sick"},
    {"h":"十","p":"shí","e":"ten"},
    {"h":"时候","p":"shíhou","e":"moment, time"},
    {"h":"时间","p":"shíjiān","e":"time"},
    {"h":"事","p":"shì","e":"matter, thing"},
    {"h":"是","p":"shì","e":"to be"},
    {"h":"手机","p":"shǒujī","e":"cell phone"},
    {"h":"书","p":"shū","e":"book"},
    {"h":"书店","p":"shūdiàn","e":"bookstore"},
    {"h":"水","p":"shuǐ","e":"water"},
    {"h":"水果","p":"shuǐguǒ","e":"fruit"},
    {"h":"睡","p":"shuì","e":"to sleep"},
    {"h":"睡觉","p":"shuìjiào","e":"to sleep"},
    {"h":"说","p":"shuō","e":"to speak, to say"},
    {"h":"说话","p":"shuōhuà","e":"to talk"},
    {"h":"四","p":"sì","e":"four"},
    {"h":"岁","p":"suì","e":"measure word for age"},
    {"h":"他","p":"tā","e":"he, him"},
    {"h":"它","p":"tā","e":"it"},
    {"h":"她","p":"tā","e":"she"},
    {"h":"他们","p":"tāmen","e":"they"},
    {"h":"它们","p":"tāmen","e":"they"},
    {"h":"她们","p":"tāmen","e":"they"},
    {"h":"太","p":"tài","e":"too, extremely"},
    {"h":"天","p":"tiān","e":"day"},
    {"h":"天气","p":"tiānqì","e":"weather"},
    {"h":"听","p":"tīng","e":"to listen"},
    {"h":"听见","p":"tīngjiàn","e":"to hear"},
    {"h":"同学","p":"tóngxué","e":"classmate"},
    {"h":"外","p":"wài","e":"outside, exterior"},
    {"h":"外边","p":"wàibian","e":"outside"},
    {"h":"玩","p":"wán","e":"to play"},
    {"h":"晚","p":"wǎn","e":"late"},
    {"h":"晚饭","p":"wǎnfàn","e":"dinner"},
    {"h":"晚上","p":"wǎnshang","e":"evening"},
    {"h":"喂","p":"wèi","e":"hello"},
    {"h":"问","p":"wèn","e":"to ask"},
    {"h":"问题","p":"wèntí","e":"question"},
    {"h":"我","p":"wǒ","e":"I"},
    {"h":"我们","p":"wǒmen","e":"we"},
    {"h":"五","p":"wǔ","e":"five"},
    {"h":"午饭","p":"wǔfàn","e":"lunch"},
    {"h":"喜欢","p":"xǐhuan","e":"to like"},
    {"h":"下","p":"xià","e":"down, below"},
    {"h":"下雨","p":"xià yǔ","e":"to rain"},
    {"h":"下班","p":"xiàbān","e":"to get off work"},
    {"h":"下课","p":"xiàkè","e":"to finish class"},
    {"h":"下午","p":"xiàwǔ","e":"afternoon"},
    {"h":"先生","p":"xiānsheng","e":"Mr., husband"},
    {"h":"现在","p":"xiànzài","e":"now"},
    {"h":"想","p":"xiǎng","e":"to think; to want"},
    {"h":"小","p":"xiǎo","e":"small"},
    {"h":"小朋友","p":"xiǎopéngyǒu","e":"little friend, child"},
    {"h":"小时","p":"xiǎoshí","e":"hour"},
    {"h":"小学","p":"xiǎoxué","e":"primary school"},
    {"h":"小学生","p":"xiǎoxuéshēng","e":"primary school student"},
    {"h":"些","p":"xiē","e":"measure word for indefinite amount"},
    {"h":"写","p":"xiě","e":"to write"},
    {"h":"谢谢","p":"xièxie","e":"to thank"},
    {"h":"新","p":"xīn","e":"new"},
    {"h":"星期","p":"xīngqī","e":"week"},
    {"h":"星期日","p":"xīngqīrì","e":"Sunday"},
    {"h":"星期天","p":"xīngqītiān","e":"Sunday"},
    {"h":"休息","p":"xiūxi","e":"to rest"},
    {"h":"学","p":"xué","e":"to learn, to study"},
    {"h":"学生","p":"xuéshēng","e":"student"},
    {"h":"学习","p":"xuéxí","e":"to study"},
    {"h":"学校","p":"xuéxiào","e":"school"},
    {"h":"雪","p":"xuě","e":"snow"},
    {"h":"要","p":"yào","e":"to want, to need"},
    {"h":"也","p":"yě","e":"also, too"},
    {"h":"一","p":"yī","e":"one"},
    {"h":"衣服","p":"yīfu","e":"clothes"},
    {"h":"医生","p":"yīshēng","e":"doctor"},
    {"h":"医院","p":"yīyuàn","e":"hospital"},
    {"h":"一半","p":"yíbàn","e":"half"},
    {"h":"一下","p":"yíxià","e":"once, a little"},
    {"h":"椅子","p":"yǐzi","e":"chair"},
    {"h":"一点儿","p":"yìdiǎnr","e":"a little, a bit"},
    {"h":"一些","p":"yìxiē","e":"some, a few"},
    {"h":"有","p":"yǒu","e":"to have, to exist"},
    {"h":"有的","p":"yǒude","e":"some of them"},
    {"h":"有点儿","p":"yǒudiǎnr","e":"a little, slightly"},
    {"h":"有些","p":"yǒuxiē","e":"some, some of"},
    {"h":"雨","p":"yǔ","e":"rain"},
    {"h":"元","p":"yuán","e":"yuan"},
    {"h":"月","p":"yuè","e":"month; moon"},
    {"h":"再","p":"zài","e":"again, then"},
    {"h":"在","p":"zài","e":"to be at; at; in the middle of"},
    {"h":"再见","p":"zàijiàn","e":"goodbye"},
    {"h":"早","p":"zǎo","e":"early"},
    {"h":"早饭","p":"zǎofàn","e":"breakfast"},
    {"h":"早上","p":"zǎoshang","e":"morning"},
    {"h":"怎么","p":"zěnme","e":"how"},
    {"h":"怎么样","p":"zěnmeyàng","e":"how about, what do you think"},
    {"h":"找","p":"zhǎo","e":"to look for"},
    {"h":"这","p":"zhè","e":"this"},
    {"h":"这边","p":"zhèbiān","e":"here"},
    {"h":"这个","p":"zhège","e":"this one"},
    {"h":"这里","p":"zhèlǐ","e":"here"},
    {"h":"这儿","p":"zhèr","e":"here"},
    {"h":"这些","p":"zhèxiē","e":"these"},
    {"h":"真","p":"zhēn","e":"really"},
    {"h":"正在","p":"zhèngzài","e":"in the process of"},
    {"h":"只","p":"zhī","e":"measure word for animals"},
    {"h":"知道","p":"zhīdào","e":"to know"},
    {"h":"中国","p":"Zhōngguó","e":"China"},
    {"h":"中文","p":"Zhōngwén","e":"Chinese language"},
    {"h":"中午","p":"zhōngwǔ","e":"noon"},
    {"h":"中学","p":"zhōngxué","e":"middle school"},
    {"h":"中学生","p":"zhōngxuéshēng","e":"middle school student"},
    {"h":"住","p":"zhù","e":"to live, to reside"},
    {"h":"桌子","p":"zhuōzi","e":"table, desk"},
    {"h":"字","p":"zì","e":"character, script"},
    {"h":"昨天","p":"zuótiān","e":"yesterday"},
    {"h":"坐","p":"zuò","e":"to sit"},
    {"h":"做","p":"zuò","e":"to do, to make"},
    {"h":"做饭","p":"zuò fàn","e":"to cook"}
  ],
  2: [
    {"h":"啊","p":"a","e":"ah, oh"},
    {"h":"爱好","p":"àihào","e":"to like; hobby"},
    {"h":"白色","p":"báisè","e":"white"},
    {"h":"班","p":"bān","e":"class, team"},
    {"h":"帮","p":"bāng","e":"to help"},
    {"h":"帮忙","p":"bāngmáng","e":"to help"},
    {"h":"包","p":"bāo","e":"to wrap, bag"},
    {"h":"本子","p":"běnzi","e":"notebook"},
    {"h":"比","p":"bǐ","e":"to compare; than"},
    {"h":"笔","p":"bǐ","e":"pen"},
    {"h":"别","p":"bié","e":"don't"},
    {"h":"不错","p":"búcuò","e":"not bad, pretty good"},
    {"h":"不好意思","p":"bù hǎoyìsi","e":"sorry, embarrassed"},
    {"h":"长","p":"cháng","e":"long"},
    {"h":"车站","p":"chēzhàn","e":"station"},
    {"h":"出","p":"chū","e":"to go out"},
    {"h":"出国","p":"chūguó","e":"to go abroad"},
    {"h":"出来","p":"chūlái","e":"to come out"},
    {"h":"出门","p":"chūmén","e":"to go out"},
    {"h":"出去","p":"chūqù","e":"to go out"},
    {"h":"床","p":"chuáng","e":"bed"},
    {"h":"词","p":"cí","e":"word, term"},
    {"h":"次","p":"cì","e":"measure word of time"},
    {"h":"从","p":"cóng","e":"from"},
    {"h":"从小","p":"cóngxiǎo","e":"from childhood"},
    {"h":"错","p":"cuò","e":"wrong, mistaken"},
    {"h":"打","p":"dǎ","e":"to hit, to play"},
    {"h":"打车","p":"dǎchē","e":"to take a taxi"},
    {"h":"打开","p":"dǎkāi","e":"to open"},
    {"h":"但","p":"dàn","e":"but, however"},
    {"h":"但是","p":"dànshì","e":"but, however"},
    {"h":"得","p":"de","e":"particle indicating degree"},
    {"h":"地","p":"de","e":"particle modifying adjective"},
    {"h":"等","p":"děng","e":"to wait"},
    {"h":"地铁","p":"dìtiě","e":"subway, metro"},
    {"h":"懂","p":"dǒng","e":"to understand"},
    {"h":"动","p":"dòng","e":"to move, to act"},
    {"h":"饭馆","p":"fànguǎn","e":"restaurant"},
    {"h":"飞","p":"fēi","e":"to fly"},
    {"h":"高","p":"gāo","e":"tall, high"},
    {"h":"高中","p":"gāozhōng","e":"high school"},
    {"h":"告诉","p":"gàosu","e":"to tell"},
    {"h":"个子","p":"gèzi","e":"height, stature"},
    {"h":"跟","p":"gēn","e":"with; and"},
    {"h":"公交车","p":"gōngjiāochē","e":"bus"},
    {"h":"过","p":"guò","e":"to pass"},
    {"h":"过来","p":"guòlái","e":"to come over"},
    {"h":"过年","p":"guònián","e":"to celebrate New Year"},
    {"h":"过去","p":"guòqù","e":"to go over"},
    {"h":"还是","p":"háishi","e":"still; or"},
    {"h":"黑色","p":"hēisè","e":"black"},
    {"h":"红茶","p":"hóngchá","e":"black tea"},
    {"h":"红色","p":"hóngsè","e":"red"},
    {"h":"后面","p":"hòumiàn","e":"behind, back"},
    {"h":"花","p":"huā","e":"to spend; flower"},
    {"h":"画","p":"huà","e":"to draw; painting"},
    {"h":"坏","p":"huài","e":"bad, broken"},
    {"h":"回来","p":"huílái","e":"to come back"},
    {"h":"回去","p":"huíqù","e":"to go back"},
    {"h":"机场","p":"jīchǎng","e":"airport"},
    {"h":"机票","p":"jīpiào","e":"airplane ticket"},
    {"h":"记得","p":"jìde","e":"to remember"},
    {"h":"间","p":"jiān","e":"measure word for rooms"},
    {"h":"教","p":"jiāo","e":"to teach"},
    {"h":"教室","p":"jiàoshì","e":"classroom"},
    {"h":"介绍","p":"jièshào","e":"to introduce"},
    {"h":"进","p":"jìn","e":"to enter"},
    {"h":"近","p":"jìn","e":"near, close"},
    {"h":"进来","p":"jìnlái","e":"to come in"},
    {"h":"进去","p":"jìnqù","e":"to go in"},
    {"h":"经常","p":"jīngcháng","e":"often"},
    {"h":"酒店","p":"jiǔdiàn","e":"hotel"},
    {"h":"就","p":"jiù","e":"just, then"},
    {"h":"咖啡","p":"kāfēi","e":"coffee"},
    {"h":"开始","p":"kāishǐ","e":"to start"},
    {"h":"开学","p":"kāixué","e":"school starts"},
    {"h":"考","p":"kǎo","e":"to test"},
    {"h":"考试","p":"kǎoshì","e":"exam"},
    {"h":"可能","p":"kěnéng","e":"possible; may"},
    {"h":"裤子","p":"kùzi","e":"pants"},
    {"h":"快","p":"kuài","e":"fast; soon"},
    {"h":"快乐","p":"kuàilè","e":"happy, joyful"},
    {"h":"快要","p":"kuàiyào","e":"soon, almost"},
    {"h":"篮球","p":"lánqiú","e":"basketball"},
    {"h":"累","p":"lèi","e":"tired"},
    {"h":"离","p":"lí","e":"to leave, away from"},
    {"h":"里面","p":"lǐmiàn","e":"inside"},
    {"h":"楼","p":"lóu","e":"building, floor"},
    {"h":"路","p":"lù","e":"road, path"},
    {"h":"路上","p":"lùshang","e":"on the road"},
    {"h":"旅游","p":"lǚyóu","e":"to travel"},
    {"h":"绿茶","p":"lǜchá","e":"green tea"},
    {"h":"绿色","p":"lǜsè","e":"green color"},
    {"h":"慢","p":"màn","e":"slow"},
    {"h":"没意思","p":"méi yìsi","e":"boring"},
    {"h":"每","p":"měi","e":"every, each"},
    {"h":"门","p":"mén","e":"door, gate"},
    {"h":"门口","p":"ménkǒu","e":"doorway, entrance"},
    {"h":"门票","p":"ménpiào","e":"ticket"},
    {"h":"面","p":"miàn","e":"side, aspect"},
    {"h":"名","p":"míng","e":"name; measure word"},
    {"h":"拿","p":"ná","e":"to take, to hold"},
    {"h":"那么","p":"nàme","e":"so, like that"},
    {"h":"那样","p":"nàyàng","e":"like that"},
    {"h":"奶茶","p":"nǎichá","e":"milk tea"},
    {"h":"奶奶","p":"nǎinai","e":"grandmother"},
    {"h":"男孩儿","p":"nánháir","e":"boy"},
    {"h":"鸟","p":"niǎo","e":"bird"},
    {"h":"女孩儿","p":"nǚháir","e":"girl"},
    {"h":"旁边","p":"pángbiān","e":"side"},
    {"h":"跑","p":"pǎo","e":"to run"},
    {"h":"跑步","p":"pǎobù","e":"to run, jogging"},
    {"h":"票","p":"piào","e":"ticket"},
    {"h":"妻子","p":"qīzi","e":"wife"},
    {"h":"起来","p":"qǐlái","e":"to get up"},
    {"h":"前面","p":"qiánmiàn","e":"front"},
    {"h":"晴","p":"qíng","e":"sunny, clear"},
    {"h":"球","p":"qiú","e":"ball, sphere"},
    {"h":"让","p":"ràng","e":"to let, to allow"},
    {"h":"肉","p":"ròu","e":"meat"},
    {"h":"商场","p":"shāngchǎng","e":"shopping mall"},
    {"h":"上来","p":"shànglái","e":"to come up"},
    {"h":"上面","p":"shàngmiàn","e":"above, top"},
    {"h":"上去","p":"shàngqù","e":"to go up"},
    {"h":"上网","p":"shàngwǎng","e":"to go online"},
    {"h":"身体","p":"shēntǐ","e":"body"},
    {"h":"生日","p":"shēngrì","e":"birthday"},
    {"h":"时","p":"shí","e":"time, moment"},
    {"h":"事情","p":"shìqing","e":"matter, affair"},
    {"h":"手","p":"shǒu","e":"hand"},
    {"h":"手表","p":"shǒubiǎo","e":"watch"},
    {"h":"书包","p":"shūbāo","e":"backpack"},
    {"h":"舒服","p":"shūfu","e":"comfortable"},
    {"h":"送","p":"sòng","e":"to give, to send"},
    {"h":"虽然","p":"suīrán","e":"although"},
    {"h":"所以","p":"suǒyǐ","e":"so, therefore"},
    {"h":"疼","p":"téng","e":"painful, sore"},
    {"h":"踢","p":"tī","e":"to kick"},
    {"h":"题","p":"tí","e":"question, problem"},
    {"h":"条","p":"tiáo","e":"measure word for long things"},
    {"h":"跳舞","p":"tiàowǔ","e":"to dance"},
    {"h":"头","p":"tóu","e":"head"},
    {"h":"外国","p":"wàiguó","e":"foreign country"},
    {"h":"外面","p":"wàimiàn","e":"outside"},
    {"h":"完","p":"wán","e":"to finish"},
    {"h":"万","p":"wàn","e":"ten thousand"},
    {"h":"往","p":"wǎng","e":"toward"},
    {"h":"网上","p":"wǎngshang","e":"online"},
    {"h":"忘","p":"wàng","e":"to forget"},
    {"h":"位","p":"wèi","e":"measure word for people"},
    {"h":"为什么","p":"wèi shénme","e":"why"},
    {"h":"希望","p":"xīwàng","e":"to hope"},
    {"h":"洗","p":"xǐ","e":"to wash"},
    {"h":"洗手间","p":"xǐshǒujiān","e":"restroom"},
    {"h":"下来","p":"xiàlái","e":"to come down"},
    {"h":"下面","p":"xiàmiàn","e":"below, under"},
    {"h":"下去","p":"xiàqù","e":"to go down"},
    {"h":"小孩儿","p":"xiǎoháir","e":"child"},
    {"h":"小时候","p":"xiǎoshíhou","e":"childhood"},
    {"h":"笑","p":"xiào","e":"to laugh, to smile"},
    {"h":"姓","p":"xìng","e":"surname"},
    {"h":"姓名","p":"xìngmíng","e":"full name"},
    {"h":"颜色","p":"yánsè","e":"color"},
    {"h":"眼睛","p":"yǎnjing","e":"eye"},
    {"h":"药","p":"yào","e":"medicine"},
    {"h":"药店","p":"yàodiàn","e":"pharmacy"},
    {"h":"爷爷","p":"yéye","e":"grandfather"},
    {"h":"一会儿","p":"yíhuìr","e":"a while, a moment"},
    {"h":"已经","p":"yǐjīng","e":"already"},
    {"h":"一起","p":"yìqǐ","e":"together"},
    {"h":"意思","p":"yìsi","e":"meaning, idea"},
    {"h":"阴","p":"yīn","e":"cloudy"},
    {"h":"因为","p":"yīnwèi","e":"because"},
    {"h":"游","p":"yóu","e":"to swim"},
    {"h":"游泳","p":"yóuyǒng","e":"to swim"},
    {"h":"有意思","p":"yǒu yìsi","e":"interesting"},
    {"h":"有时","p":"yǒushí","e":"sometimes"},
    {"h":"右","p":"yòu","e":"right"},
    {"h":"右边","p":"yòubian","e":"right side"},
    {"h":"鱼","p":"yú","e":"fish"},
    {"h":"远","p":"yuǎn","e":"far"},
    {"h":"运动","p":"yùndòng","e":"to exercise; sports"},
    {"h":"站","p":"zhàn","e":"station; to stand"},
    {"h":"丈夫","p":"zhàngfu","e":"husband"},
    {"h":"这么","p":"zhème","e":"so, such"},
    {"h":"这样","p":"zhèyàng","e":"like this, so"},
    {"h":"着","p":"zhe","e":"particle indicating ongoing action"},
    {"h":"正","p":"zhèng","e":"just, exactly"},
    {"h":"周","p":"zhōu","e":"week"},
    {"h":"准备","p":"zhǔnbèi","e":"to prepare"},
    {"h":"自己","p":"zìjǐ","e":"oneself"},
    {"h":"走","p":"zǒu","e":"to walk"},
    {"h":"走路","p":"zǒulù","e":"to walk"},
    {"h":"足球","p":"zúqiú","e":"soccer, football"},
    {"h":"最","p":"zuì","e":"most, -est"},
    {"h":"左","p":"zuǒ","e":"left"},
    {"h":"左边","p":"zuǒbian","e":"left side"}
  ],
  3: [
    {"h":"阿姨","p":"āyí","e":"aunt"},
    {"h":"矮","p":"ǎi","e":"short"},
    {"h":"爱人","p":"àiren","e":"spouse"},
    {"h":"安静","p":"ānjìng","e":"quiet"},
    {"h":"安全","p":"ānquán","e":"safe"},
    {"h":"把","p":"bǎ","e":"measure word; particle"},
    {"h":"搬","p":"bān","e":"to move, to carry"},
    {"h":"班级","p":"bānjí","e":"class, grade"},
    {"h":"搬家","p":"bānjiā","e":"to move house"},
    {"h":"办","p":"bàn","e":"to do, to handle"},
    {"h":"办法","p":"bànfǎ","e":"way, solution"},
    {"h":"办公室","p":"bàngōngshì","e":"office"},
    {"h":"半天","p":"bàntiān","e":"half a day"},
    {"h":"帮助","p":"bāngzhù","e":"help"},
    {"h":"饱","p":"bǎo","e":"full"},
    {"h":"报纸","p":"bàozhǐ","e":"newspaper"},
    {"h":"北","p":"běi","e":"north"},
    {"h":"北方","p":"běifāng","e":"north"},
    {"h":"被","p":"bèi","e":"by"},
    {"h":"笔记","p":"bǐjì","e":"notes"},
    {"h":"比较","p":"bǐjiào","e":"to compare; quite"},
    {"h":"笔记本","p":"bǐjìběn","e":"notebook"},
    {"h":"比如","p":"bǐrú","e":"for example"},
    {"h":"比赛","p":"bǐsài","e":"to compete; game"},
    {"h":"必须","p":"bìxū","e":"must"},
    {"h":"变","p":"biàn","e":"to change"},
    {"h":"遍","p":"biàn","e":"measure word for actions"},
    {"h":"变成","p":"biànchéng","e":"to become"},
    {"h":"变化","p":"biànhuà","e":"to change; change"},
    {"h":"表演","p":"biǎoyǎn","e":"to perform"},
    {"h":"别的","p":"biéde","e":"other"},
    {"h":"别人","p":"biérén","e":"other people"},
    {"h":"宾馆","p":"bīnguǎn","e":"hotel"},
    {"h":"冰","p":"bīng","e":"ice"},
    {"h":"冰激凌","p":"bīngjīlíng","e":"ice cream"},
    {"h":"冰箱","p":"bīngxiāng","e":"refrigerator"},
    {"h":"病人","p":"bìngrén","e":"patient"},
    {"h":"不但","p":"búdàn","e":"not only"},
    {"h":"不见","p":"bújiàn","e":"to disappear"},
    {"h":"不用","p":"búyòng","e":"need not"},
    {"h":"不同","p":"bù tóng","e":"different"},
    {"h":"不久","p":"bùjiǔ","e":"soon"},
    {"h":"不行","p":"bùxíng","e":"not allowed"},
    {"h":"才","p":"cái","e":"just, only"},
    {"h":"菜单","p":"càidān","e":"menu"},
    {"h":"参加","p":"cānjiā","e":"to join, to attend"},
    {"h":"草","p":"cǎo","e":"grass"},
    {"h":"草地","p":"cǎodì","e":"grassland"},
    {"h":"层","p":"céng","e":"measure word for floors"},
    {"h":"查","p":"chá","e":"to check"},
    {"h":"差","p":"chà","e":"bad, poor"},
    {"h":"差不多","p":"chàbuduō","e":"almost, similar"},
    {"h":"尝","p":"cháng","e":"to taste"},
    {"h":"常","p":"cháng","e":"often"},
    {"h":"常见","p":"cháng jiàn","e":"common"},
    {"h":"常用","p":"cháng yòng","e":"commonly used"},
    {"h":"常常","p":"chángcháng","e":"often"},
    {"h":"衬衫","p":"chènshān","e":"shirt"},
    {"h":"成绩","p":"chéngjì","e":"score, grade"},
    {"h":"城市","p":"chéngshì","e":"city"},
    {"h":"迟到","p":"chídào","e":"to be late"},
    {"h":"出发","p":"chūfā","e":"to set out"},
    {"h":"出生","p":"chūshēng","e":"to be born"},
    {"h":"出院","p":"chūyuàn","e":"to be discharged"},
    {"h":"初中","p":"chūzhōng","e":"junior high school"},
    {"h":"除了","p":"chúle","e":"except, besides"},
    {"h":"船","p":"chuán","e":"boat"},
    {"h":"春天","p":"chūntiān","e":"spring"},
    {"h":"词典","p":"cídiǎn","e":"dictionary"},
    {"h":"聪明","p":"cōngmíng","e":"smart, clever"},
    {"h":"打扫","p":"dǎsǎo","e":"to clean"},
    {"h":"打算","p":"dǎsuàn","e":"to plan; plan"},
    {"h":"大概","p":"dàgài","e":"probably"},
    {"h":"大人","p":"dàren","e":"adult"},
    {"h":"大小","p":"dàxiǎo","e":"size"},
    {"h":"大熊猫","p":"dàxióngmāo","e":"giant panda"},
    {"h":"大衣","p":"dàyī","e":"coat"},
    {"h":"带","p":"dài","e":"to bring, to take"},
    {"h":"担心","p":"dānxīn","e":"to worry"},
    {"h":"蛋糕","p":"dàngāo","e":"cake"},
    {"h":"当然","p":"dāngrán","e":"of course"},
    {"h":"到处","p":"dàochù","e":"everywhere"},
    {"h":"得","p":"dé","e":"to get, to obtain"},
    {"h":"得到","p":"dédào","e":"to get"},
    {"h":"得分","p":"défēn","e":"to score"},
    {"h":"的话","p":"dehuà","e":"if"},
    {"h":"得","p":"děi","e":"must, need"},
    {"h":"灯","p":"dēng","e":"lamp, light"},
    {"h":"地","p":"dì","e":"ground, earth"},
    {"h":"地点","p":"dìdiǎn","e":"place, location"},
    {"h":"地方","p":"dìfang","e":"place"},
    {"h":"地图","p":"dìtú","e":"map"},
    {"h":"电","p":"diàn","e":"electricity"},
    {"h":"电梯","p":"diàntī","e":"elevator"},
    {"h":"电子书","p":"diànzǐshū","e":"e-book"},
    {"h":"丢","p":"diū","e":"to lose, to throw"},
    {"h":"东","p":"dōng","e":"east"},
    {"h":"东北","p":"dōngběi","e":"northeast"},
    {"h":"东方","p":"dōngfāng","e":"east"},
    {"h":"东南","p":"dōngnán","e":"southeast"},
    {"h":"冬天","p":"dōngtiān","e":"winter"},
    {"h":"懂得","p":"dǒngde","e":"to understand"},
    {"h":"动物","p":"dòngwù","e":"animal"},
    {"h":"动物园","p":"dòngwùyuán","e":"zoo"},
    {"h":"短","p":"duǎn","e":"short"},
    {"h":"短裤","p":"duǎnkù","e":"shorts"},
    {"h":"段","p":"duàn","e":"measure word for segment"},
    {"h":"锻炼","p":"duànliàn","e":"to exercise"},
    {"h":"对话","p":"duìhuà","e":"dialogue"},
    {"h":"饿","p":"è","e":"hungry"},
    {"h":"而且","p":"érqiě","e":"and, moreover"},
    {"h":"耳朵","p":"ěrduo","e":"ear"},
    {"h":"耳机","p":"ěrjī","e":"earphone"},
    {"h":"发","p":"fā","e":"to send, to issue"},
    {"h":"发烧","p":"fāshāo","e":"to have a fever"},
    {"h":"发生","p":"fāshēng","e":"to happen"},
    {"h":"发现","p":"fāxiàn","e":"to find, to discover"},
    {"h":"发展","p":"fāzhǎn","e":"to develop"},
    {"h":"方便","p":"fāngbiàn","e":"convenient"},
    {"h":"方便面","p":"fāngbiànmiàn","e":"instant noodles"},
    {"h":"方法","p":"fāngfǎ","e":"method"},
    {"h":"方向","p":"fāngxiàng","e":"direction"},
    {"h":"房子","p":"fángzi","e":"house"},
    {"h":"放","p":"fàng","e":"to put, to place"},
    {"h":"放假","p":"fàngjià","e":"to have a holiday"},
    {"h":"放心","p":"fàngxīn","e":"to relax"},
    {"h":"放学","p":"fàngxué","e":"school is over"},
    {"h":"分开","p":"fēnkāi","e":"to separate"},
    {"h":"风","p":"fēng","e":"wind"},
    {"h":"封","p":"fēng","e":"measure word for letters"},
    {"h":"夫妻","p":"fūqī","e":"husband and wife"},
    {"h":"服务","p":"fúwù","e":"to serve"},
    {"h":"附近","p":"fùjìn","e":"nearby"},
    {"h":"复习","p":"fùxí","e":"to review"},
    {"h":"该","p":"gāi","e":"should"},
    {"h":"干净","p":"gānjìng","e":"clean"},
    {"h":"感兴趣","p":"gǎn xìngqù","e":"to be interested in"},
    {"h":"感到","p":"gǎndào","e":"to feel"},
    {"h":"感冒","p":"gǎnmào","e":"cold; to catch a cold"},
    {"h":"干","p":"gàn","e":"to do, to work"},
    {"h":"刚","p":"gāng","e":"just, just now"},
    {"h":"刚才","p":"gāngcái","e":"just now"},
    {"h":"刚刚","p":"gānggāng","e":"just now"},
    {"h":"高铁","p":"gāotiě","e":"high-speed rail"},
    {"h":"根据","p":"gēnjù","e":"according to"},
    {"h":"更","p":"gèng","e":"more"},
    {"h":"公斤","p":"gōngjīn","e":"kilogram"},
    {"h":"公园","p":"gōngyuán","e":"park"},
    {"h":"工作日","p":"gōngzuòrì","e":"workday"},
    {"h":"故事","p":"gùshi","e":"story"},
    {"h":"刮","p":"guā","e":"to scrape, to blow"},
    {"h":"关","p":"guān","e":"to close"},
    {"h":"关机","p":"guānjī","e":"to turn off"},
    {"h":"关系","p":"guānxì","e":"relationship"},
    {"h":"关心","p":"guānxīn","e":"to care about"},
    {"h":"关于","p":"guānyú","e":"about, regarding"},
    {"h":"关注","p":"guānzhù","e":"to pay attention to"},
    {"h":"国家","p":"guójiā","e":"country"},
    {"h":"过节","p":"guòjié","e":"to celebrate a festival"},
    {"h":"过去","p":"guòqù","e":"past"},
    {"h":"海","p":"hǎi","e":"sea"},
    {"h":"害怕","p":"hàipà","e":"to be afraid"},
    {"h":"好多","p":"hǎoduō","e":"many, a lot"},
    {"h":"好久","p":"hǎojiǔ","e":"a long time"},
    {"h":"好像","p":"hǎoxiàng","e":"to seem, as if"},
    {"h":"号码","p":"hàomǎ","e":"number, code"},
    {"h":"河","p":"hé","e":"river"},
    {"h":"合适","p":"héshì","e":"suitable"},
    {"h":"黑板","p":"hēibǎn","e":"blackboard"},
    {"h":"红绿灯","p":"hóng-lǜdēng","e":"traffic light"},
    {"h":"后来","p":"hòulái","e":"later, afterwards"},
    {"h":"后年","p":"hòunián","e":"the year after next"},
    {"h":"后天","p":"hòutiān","e":"the day after tomorrow"},
    {"h":"护照","p":"hùzhào","e":"passport"},
    {"h":"花园","p":"huāyuán","e":"garden"},
    {"h":"画家","p":"huàjiā","e":"painter, artist"},
    {"h":"欢迎","p":"huānyíng","e":"to welcome"},
    {"h":"还","p":"huán","e":"to return, to give back"},
    {"h":"环境","p":"huánjìng","e":"environment"},
    {"h":"换","p":"huàn","e":"to exchange"},
    {"h":"黄色","p":"huángsè","e":"yellow"},
    {"h":"回答","p":"huídá","e":"to answer"},
    {"h":"会","p":"huì","e":"meeting"},
    {"h":"会议","p":"huìyì","e":"meeting"},
    {"h":"或","p":"huò","e":"or"},
    {"h":"或者","p":"huòzhě","e":"or"},
    {"h":"鸡","p":"jī","e":"chicken"},
    {"h":"几乎","p":"jīhū","e":"almost"},
    {"h":"机会","p":"jīhuì","e":"opportunity"},
    {"h":"极","p":"jí","e":"extremely"},
    {"h":"急","p":"jí","e":"urgent"},
    {"h":"记","p":"jì","e":"to remember"},
    {"h":"季","p":"jì","e":"season"},
    {"h":"季节","p":"jìjié","e":"season"},
    {"h":"加","p":"jiā","e":"to add"},
    {"h":"假期","p":"jiàqī","e":"vacation"},
    {"h":"坚持","p":"jiānchí","e":"to persist"},
    {"h":"检查","p":"jiǎnchá","e":"to check"},
    {"h":"简单","p":"jiǎndān","e":"simple"},
    {"h":"检票","p":"jiǎnpiào","e":"ticket checking"},
    {"h":"健康","p":"jiànkāng","e":"healthy"},
    {"h":"见面","p":"jiànmiàn","e":"to meet"},
    {"h":"讲","p":"jiǎng","e":"to speak"},
    {"h":"角","p":"jiǎo","e":"measure word; angle"},
    {"h":"脚","p":"jiǎo","e":"foot"},
    {"h":"接","p":"jiē","e":"to pick up, to receive"},
    {"h":"街","p":"jiē","e":"street"},
    {"h":"节","p":"jié","e":"measure word; festival"},
    {"h":"结婚","p":"jiéhūn","e":"to marry"},
    {"h":"节目","p":"jiémù","e":"program"},
    {"h":"节日","p":"jiérì","e":"festival"},
    {"h":"结束","p":"jiéshù","e":"to end"},
    {"h":"解决","p":"jiějué","e":"to solve"},
    {"h":"姐妹","p":"jiěmèi","e":"sister"},
    {"h":"借","p":"jiè","e":"to borrow"},
    {"h":"斤","p":"jīn","e":"catty"},
    {"h":"经过","p":"jīngguò","e":"to pass; process"},
    {"h":"经理","p":"jīnglǐ","e":"manager"},
    {"h":"久","p":"jiǔ","e":"long"},
    {"h":"酒","p":"jiǔ","e":"alcohol"},
    {"h":"旧","p":"jiù","e":"old"},
    {"h":"句","p":"jù","e":"measure word of sentence"},
    {"h":"句子","p":"jùzi","e":"sentence"},
    {"h":"决定","p":"juédìng","e":"to decide; decision"},
    {"h":"卡","p":"kǎ","e":"card"},
    {"h":"开花","p":"kāihuā","e":"to bloom"},
    {"h":"开会","p":"kāihuì","e":"to have a meeting"},
    {"h":"开机","p":"kāijī","e":"to turn on"},
    {"h":"开心","p":"kāixīn","e":"happy"},
    {"h":"看来","p":"kànlái","e":"it seems"},
    {"h":"可","p":"kě","e":"but"},
    {"h":"渴","p":"kě","e":"thirsty"},
    {"h":"可爱","p":"kě'ài","e":"lovely"},
    {"h":"可是","p":"kěshì","e":"but"},
    {"h":"刻","p":"kè","e":"quarter; to carve"},
    {"h":"课本","p":"kèběn","e":"textbook"},
    {"h":"客人","p":"kèrén","e":"guest"},
    {"h":"课文","p":"kèwén","e":"text"},
    {"h":"空调","p":"kōngtiáo","e":"air conditioner"},
    {"h":"哭","p":"kū","e":"to cry"},
    {"h":"筷子","p":"kuàizi","e":"chopsticks"},
    {"h":"矿泉水","p":"kuàngquánshuǐ","e":"mineral water"},
    {"h":"来自","p":"láizì","e":"to come from"},
    {"h":"蓝","p":"lán","e":"blue"},
    {"h":"老","p":"lǎo","e":"old, aged"},
    {"h":"老人","p":"lǎorén","e":"elderly person"},
    {"h":"离开","p":"líkāi","e":"to leave"},
    {"h":"礼物","p":"lǐwù","e":"gift"},
    {"h":"历史","p":"lìshǐ","e":"history"},
    {"h":"脸","p":"liǎn","e":"face"},
    {"h":"练","p":"liàn","e":"to practice"},
    {"h":"练习","p":"liànxí","e":"to practice; exercise"},
    {"h":"凉快","p":"liángkuai","e":"cool"},
    {"h":"辆","p":"liàng","e":"measure word for vehicles"},
    {"h":"聊","p":"liáo","e":"to chat"},
    {"h":"聊天儿","p":"liáotiānr","e":"to chat"},
    {"h":"了解","p":"liǎojiě","e":"to understand"},
    {"h":"邻居","p":"línjū","e":"neighbor"},
    {"h":"留学","p":"liúxué","e":"to study abroad"},
    {"h":"留学生","p":"liúxuéshēng","e":"overseas student"},
    {"h":"楼梯","p":"lóutī","e":"stairs"},
    {"h":"路边","p":"lùbiān","e":"roadside"},
    {"h":"路口","p":"lùkǒu","e":"intersection"},
    {"h":"马","p":"mǎ","e":"horse"},
    {"h":"马路","p":"mǎlù","e":"road"},
    {"h":"马上","p":"mǎshàng","e":"immediately"},
    {"h":"满意","p":"mǎnyì","e":"satisfied"},
    {"h":"毛","p":"máo","e":"measure word for money"},
    {"h":"米","p":"mǐ","e":"meter"},
    {"h":"面前","p":"miànqián","e":"in front of"},
    {"h":"明白","p":"míngbai","e":"to understand; clear"},
    {"h":"名单","p":"míngdān","e":"name list"},
    {"h":"名人","p":"míngrén","e":"famous person"},
    {"h":"南","p":"nán","e":"south"},
    {"h":"难","p":"nán","e":"difficult"},
    {"h":"南方","p":"nánfāng","e":"south"},
    {"h":"难过","p":"nánguò","e":"sad"},
    {"h":"难看","p":"nánkàn","e":"ugly"},
    {"h":"男人","p":"nánrén","e":"man"},
    {"h":"男生","p":"nánshēng","e":"boy student"},
    {"h":"难题","p":"nántí","e":"difficult problem"},
    {"h":"难听","p":"nántīng","e":"unpleasant to hear"},
    {"h":"年级","p":"niánjí","e":"grade"},
    {"h":"年轻","p":"niánqīng","e":"young"},
    {"h":"牛","p":"niú","e":"cow"},
    {"h":"努力","p":"nǔlì","e":"to work hard"},
    {"h":"女人","p":"nǚrén","e":"woman"},
    {"h":"女生","p":"nǚshēng","e":"girl student"},
    {"h":"爬","p":"pá","e":"to climb"},
    {"h":"怕","p":"pà","e":"to fear"},
    {"h":"拍照","p":"pāizhào","e":"to take a photo"},
    {"h":"盘子","p":"pánzi","e":"plate"},
    {"h":"胖","p":"pàng","e":"fat"},
    {"h":"啤酒","p":"píjiǔ","e":"beer"},
    {"h":"平时","p":"píngshí","e":"usually"},
    {"h":"瓶子","p":"píngzi","e":"bottle"},
    {"h":"骑","p":"qí","e":"to ride"},
    {"h":"奇怪","p":"qíguài","e":"strange"},
    {"h":"其实","p":"qíshí","e":"actually"},
    {"h":"其他","p":"qítā","e":"other"},
    {"h":"起","p":"qǐ","e":"to rise, to get up"},
    {"h":"起飞","p":"qǐfēi","e":"to take off"},
    {"h":"汽车","p":"qìchē","e":"car"},
    {"h":"铅笔","p":"qiānbǐ","e":"pencil"},
    {"h":"前年","p":"qiánnián","e":"year before last"},
    {"h":"前天","p":"qiántiān","e":"day before yesterday"},
    {"h":"清楚","p":"qīngchu","e":"clear, obvious"},
    {"h":"请假","p":"qǐngjià","e":"to ask for leave"},
    {"h":"请客","p":"qǐngkè","e":"to treat someone"},
    {"h":"秋天","p":"qiūtiān","e":"autumn"},
    {"h":"球场","p":"qiúchǎng","e":"sports field"},
    {"h":"裙子","p":"qúnzi","e":"skirt"},
    {"h":"然后","p":"ránhòu","e":"then, afterwards"},
    {"h":"热情","p":"rèqíng","e":"enthusiastic"},
    {"h":"认得","p":"rènde","e":"to recognize"},
    {"h":"认为","p":"rènwéi","e":"to think"},
    {"h":"认真","p":"rènzhēn","e":"serious, earnest"},
    {"h":"容易","p":"róngyì","e":"easy"},
    {"h":"如果","p":"rúguǒ","e":"if"},
    {"h":"伞","p":"sǎn","e":"umbrella"},
    {"h":"扫","p":"sǎo","e":"to sweep"},
    {"h":"沙发","p":"shāfā","e":"sofa"},
    {"h":"山","p":"shān","e":"mountain"},
    {"h":"上衣","p":"shàngyī","e":"jacket, top"},
    {"h":"勺子","p":"sháozi","e":"spoon"},
    {"h":"身边","p":"shēnbiān","e":"by one's side"},
    {"h":"身高","p":"shēngāo","e":"height"},
    {"h":"声","p":"shēng","e":"sound, voice"},
    {"h":"生活","p":"shēnghuó","e":"life; to live"},
    {"h":"生气","p":"shēngqì","e":"to get angry"},
    {"h":"声音","p":"shēngyīn","e":"sound"},
    {"h":"市","p":"shì","e":"city"},
    {"h":"试","p":"shì","e":"to try"},
    {"h":"室","p":"shì","e":"room"},
    {"h":"世界","p":"shìjiè","e":"world"},
    {"h":"收","p":"shōu","e":"to receive"},
    {"h":"收到","p":"shōudào","e":"to receive"},
    {"h":"受","p":"shòu","e":"to receive"},
    {"h":"瘦","p":"shòu","e":"thin, slim"},
    {"h":"受到","p":"shòudào","e":"to receive"},
    {"h":"叔叔","p":"shūshu","e":"uncle"},
    {"h":"树","p":"shù","e":"tree"},
    {"h":"数学","p":"shùxué","e":"mathematics"},
    {"h":"刷","p":"shuā","e":"to brush"},
    {"h":"双","p":"shuāng","e":"pair"},
    {"h":"水平","p":"shuǐpíng","e":"level, standard"},
    {"h":"司机","p":"sījī","e":"driver"},
    {"h":"四季","p":"sìjì","e":"four seasons"},
    {"h":"太阳","p":"tàiyáng","e":"sun"},
    {"h":"糖","p":"táng","e":"candy, sugar"},
    {"h":"特别","p":"tèbié","e":"special; particularly"},
    {"h":"提高","p":"tígāo","e":"to raise, to improve"},
    {"h":"体育","p":"tǐyù","e":"physical education"},
    {"h":"体育馆","p":"tǐyùguǎn","e":"gymnasium"},
    {"h":"甜","p":"tián","e":"sweet"},
    {"h":"跳","p":"tiào","e":"to jump"},
    {"h":"听说","p":"tīngshuō","e":"to hear said"},
    {"h":"挺","p":"tǐng","e":"quite, rather"},
    {"h":"同事","p":"tóngshì","e":"colleague"},
    {"h":"同意","p":"tóngyì","e":"to agree"},
    {"h":"头发","p":"tóufa","e":"hair"},
    {"h":"突然","p":"tūrán","e":"sudden"},
    {"h":"图书馆","p":"túshūguǎn","e":"library"},
    {"h":"腿","p":"tuǐ","e":"leg"},
    {"h":"外地","p":"wàidì","e":"other place"},
    {"h":"外卖","p":"wàimài","e":"takeaway"},
    {"h":"外语","p":"wàiyǔ","e":"foreign language"},
    {"h":"完成","p":"wánchéng","e":"to complete"},
    {"h":"碗","p":"wǎn","e":"bowl"},
    {"h":"晚点","p":"wǎndiǎn","e":"to be late"},
    {"h":"晚会","p":"wǎnhuì","e":"evening party"},
    {"h":"网球","p":"wǎngqiú","e":"tennis"},
    {"h":"网站","p":"wǎngzhàn","e":"website"},
    {"h":"忘记","p":"wàngjì","e":"to forget"},
    {"h":"为","p":"wèi","e":"for, because of"},
    {"h":"为了","p":"wèile","e":"in order to"},
    {"h":"卫生间","p":"wèishēngjiān","e":"bathroom"},
    {"h":"文化","p":"wénhuà","e":"culture"},
    {"h":"屋子","p":"wūzi","e":"room, house"},
    {"h":"西","p":"xī","e":"west"},
    {"h":"西北","p":"xīběi","e":"northwest"},
    {"h":"西方","p":"xīfāng","e":"west"},
    {"h":"西瓜","p":"xīguā","e":"watermelon"},
    {"h":"西南","p":"xīnán","e":"southwest"},
    {"h":"习惯","p":"xíguàn","e":"habit; to be used to"},
    {"h":"喜爱","p":"xǐ'ài","e":"to like, to love"},
    {"h":"洗衣机","p":"xǐyījī","e":"washing machine"},
    {"h":"洗澡","p":"xǐzǎo","e":"to take a bath"},
    {"h":"夏天","p":"xiàtiān","e":"summer"},
    {"h":"先","p":"xiān","e":"first, before"},
    {"h":"香蕉","p":"xiāngjiāo","e":"banana"},
    {"h":"相信","p":"xiāngxìn","e":"to believe"},
    {"h":"箱子","p":"xiāngzi","e":"box, case"},
    {"h":"向","p":"xiàng","e":"toward, to"},
    {"h":"像","p":"xiàng","e":"to resemble, to be like"},
    {"h":"相机","p":"xiàngjī","e":"camera"},
    {"h":"小区","p":"xiǎoqū","e":"residential community"},
    {"h":"小心","p":"xiǎoxīn","e":"to be careful"},
    {"h":"校园","p":"xiàoyuán","e":"campus"},
    {"h":"校长","p":"xiàozhǎng","e":"principal"},
    {"h":"鞋","p":"xié","e":"shoe"},
    {"h":"心里","p":"xīnlǐ","e":"heart, mind"},
    {"h":"新年","p":"xīnnián","e":"New Year"},
    {"h":"新闻","p":"xīnwén","e":"news"},
    {"h":"新鲜","p":"xīnxiān","e":"fresh"},
    {"h":"信","p":"xìn","e":"to believe; letter"},
    {"h":"信用卡","p":"xìnyòngkǎ","e":"credit card"},
    {"h":"行","p":"xíng","e":"to go; okay"},
    {"h":"行李","p":"xíngli","e":"luggage"},
    {"h":"兴趣","p":"xìngqù","e":"interest"},
    {"h":"休假","p":"xiūjià","e":"to take a holiday"},
    {"h":"需要","p":"xūyào","e":"to need; need"},
    {"h":"选","p":"xuǎn","e":"to choose"},
    {"h":"选择","p":"xuǎnzé","e":"to choose"},
    {"h":"学期","p":"xuéqī","e":"semester"},
    {"h":"牙","p":"yá","e":"tooth"},
    {"h":"牙刷","p":"yáshuā","e":"toothbrush"},
    {"h":"羊","p":"yáng","e":"sheep"},
    {"h":"养","p":"yǎng","e":"to raise, to keep"},
    {"h":"要求","p":"yāoqiú","e":"to demand; requirement"},
    {"h":"页","p":"yè","e":"page"},
    {"h":"一定","p":"yídìng","e":"certain; certainly"},
    {"h":"一共","p":"yígòng","e":"altogether"},
    {"h":"一块儿","p":"yíkuàir","e":"together"},
    {"h":"一样","p":"yíyàng","e":"same"},
    {"h":"以后","p":"yǐhòu","e":"later, after"},
    {"h":"以前","p":"yǐqián","e":"before"},
    {"h":"以上","p":"yǐshàng","e":"above, more than"},
    {"h":"以外","p":"yǐwài","e":"except, besides"},
    {"h":"以为","p":"yǐwéi","e":"to think"},
    {"h":"以下","p":"yǐxià","e":"below, less than"},
    {"h":"一般","p":"yìbān","e":"general, ordinary"},
    {"h":"一边","p":"yìbiān","e":"at the same time"},
    {"h":"一直","p":"yìzhí","e":"always, straight"},
    {"h":"音乐","p":"yīnyuè","e":"music"},
    {"h":"银行","p":"yínháng","e":"bank"},
    {"h":"银行卡","p":"yínhángkǎ","e":"bank card"},
    {"h":"饮料","p":"yǐnliào","e":"beverage"},
    {"h":"应该","p":"yīnggāi","e":"should"},
    {"h":"影响","p":"yǐngxiǎng","e":"to affect; influence"},
    {"h":"用","p":"yòng","e":"to use"},
    {"h":"邮件","p":"yóujiàn","e":"mail"},
    {"h":"游客","p":"yóukè","e":"tourist"},
    {"h":"游戏","p":"yóuxì","e":"game"},
    {"h":"邮箱","p":"yóuxiāng","e":"mailbox"},
    {"h":"有关","p":"yǒuguān","e":"concerning"},
    {"h":"有名","p":"yǒumíng","e":"famous"},
    {"h":"有用","p":"yǒuyòng","e":"useful"},
    {"h":"又","p":"yòu","e":"again, also"},
    {"h":"羽毛球","p":"yǔmáoqiú","e":"badminton"},
    {"h":"语言","p":"yǔyán","e":"language"},
    {"h":"雨衣","p":"yǔyī","e":"raincoat"},
    {"h":"遇到","p":"yùdào","e":"to encounter"},
    {"h":"遇见","p":"yùjiàn","e":"to meet"},
    {"h":"园","p":"yuán","e":"garden"},
    {"h":"员","p":"yuán","e":"suffix for person"},
    {"h":"愿意","p":"yuànyì","e":"willing"},
    {"h":"越","p":"yuè","e":"more, increasingly"},
    {"h":"月亮","p":"yuèliang","e":"moon"},
    {"h":"运动会","p":"yùndònghuì","e":"sports meet"},
    {"h":"运动员","p":"yùndòngyuán","e":"athlete"},
    {"h":"咱们","p":"zánmen","e":"we"},
    {"h":"脏","p":"zāng","e":"dirty"},
    {"h":"怎么办","p":"zěnme bàn","e":"what to do"},
    {"h":"怎样","p":"zěnyàng","e":"how"},
    {"h":"张","p":"zhāng","e":"measure word for flat objects"},
    {"h":"长","p":"zhǎng","e":"to grow"},
    {"h":"着急","p":"zháojí","e":"anxious"},
    {"h":"照","p":"zhào","e":"to shine, to photograph"},
    {"h":"照顾","p":"zhàogù","e":"to take care of"},
    {"h":"照片","p":"zhàopiàn","e":"photo"},
    {"h":"照相","p":"zhàoxiàng","e":"to take a picture"},
    {"h":"直到","p":"zhídào","e":"until"},
    {"h":"只","p":"zhǐ","e":"only, merely"},
    {"h":"纸","p":"zhǐ","e":"paper"},
    {"h":"只能","p":"zhǐ néng","e":"can only"},
    {"h":"只是","p":"zhǐshì","e":"only, merely"},
    {"h":"只要","p":"zhǐyào","e":"as long as"},
    {"h":"只有","p":"zhǐyǒu","e":"only if"},
    {"h":"中","p":"zhōng","e":"middle"},
    {"h":"中间","p":"zhōngjiān","e":"middle, between"},
    {"h":"终于","p":"zhōngyú","e":"finally"},
    {"h":"种","p":"zhǒng","e":"measure word for kinds"},
    {"h":"重要","p":"zhòngyào","e":"important"},
    {"h":"周末","p":"zhōumò","e":"weekend"},
    {"h":"主要","p":"zhǔyào","e":"main"},
    {"h":"注意","p":"zhùyì","e":"to pay attention to"},
    {"h":"住院","p":"zhùyuàn","e":"to be hospitalized"},
    {"h":"字典","p":"zìdiǎn","e":"dictionary"},
    {"h":"自行车","p":"zìxíngchē","e":"bicycle"},
    {"h":"子","p":"zi","e":"noun suffix"},
    {"h":"总","p":"zǒng","e":"always; total"},
    {"h":"总是","p":"zǒngshì","e":"always"},
    {"h":"嘴","p":"zuǐ","e":"mouth"},
    {"h":"最好","p":"zuìhǎo","e":"best"},
    {"h":"最后","p":"zuìhòu","e":"last, final"},
    {"h":"最近","p":"zuìjìn","e":"recently"},
    {"h":"做客","p":"zuòkè","e":"to be a guest"},
    {"h":"作业","p":"zuòyè","e":"homework"}
  ]
};

// Level info for UI
const HSK_LEVELS = {
  elementary: [1, 2, 3],
  intermediate: [4, 5, 6],
  advanced: [7, 8, 9]
};

const HSK_INFO = {
  1: { name: "HSK 1", words: 300, tier: "elementary" },
  2: { name: "HSK 2", words: 300, tier: "elementary" },
  3: { name: "HSK 3", words: 600, tier: "elementary" },
  4: { name: "HSK 4", words: 1200, tier: "intermediate" },
  5: { name: "HSK 5", words: 2500, tier: "intermediate" },
  6: { name: "HSK 6", words: 5000, tier: "intermediate" },
  7: { name: "HSK 7-9", words: 11000, tier: "advanced" }
};
