// HSK 3.0 Vocabulary organized by level
const HSK = {
  1: [
    {"h":"爱","p":"ài","e":"to love"},
    {"h":"八","p":"bā","e":"eight"},
    {"h":"爸爸","p":"bàba","e":"dad"},
    {"h":"吧","p":"ba","e":"particle indicating suggestion, confirmation, or hesitation"},
    {"h":"白天","p":"báitiān","e":"daytime"},
    {"h":"百","p":"bǎi","e":"hundred"},
    {"h":"半","p":"bàn","e":"half"},
    {"h":"包子","p":"bāozi","e":"steamed stuffed bun"},
    {"h":"杯子","p":"bēizi","e":"cup, glass"},
    {"h":"本","p":"běn","e":"measure word for books"},
    {"h":"边","p":"biān","e":"side"},
    {"h":"病","p":"bìng","e":"illness, disease"},
    {"h":"不","p":"bù","e":"not, no"},
    {"h":"不客气","p":"bú kèqi","e":"you're welcome"},
    {"h":"不要","p":"búyào","e":"don't, not want"},
    {"h":"菜","p":"cài","e":"vegetable, dish"},
    {"h":"茶","p":"chá","e":"tea"},
    {"h":"唱","p":"chàng","e":"to sing"},
    {"h":"超市","p":"chāoshì","e":"supermarket"},
    {"h":"车","p":"chē","e":"vehicle, car"},
    {"h":"吃","p":"chī","e":"to eat"},
    {"h":"出租车","p":"chūzūchē","e":"taxi"},
    {"h":"穿","p":"chuān","e":"to wear"},
    {"h":"打电话","p":"dǎ diànhuà","e":"to make a phone call"},
    {"h":"大","p":"dà","e":"big"},
    {"h":"大家","p":"dàjiā","e":"everyone"},
    {"h":"大学","p":"dàxué","e":"university"},
    {"h":"大学生","p":"dàxuéshēng","e":"university student"},
    {"h":"到","p":"dào","e":"to arrive"},
    {"h":"的","p":"de","e":"possessive or modifying particle"},
    {"h":"第","p":"dì","e":"prefix for ordinal numbers"},
    {"h":"弟弟","p":"dìdi","e":"younger brother"},
    {"h":"点","p":"diǎn","e":"measure word for small round things"},
    {"h":"店","p":"diàn","e":"shop, store"},
    {"h":"电话","p":"diànhuà","e":"telephone, phone call"},
    {"h":"电脑","p":"diànnǎo","e":"computer"},
    {"h":"电视","p":"diànshì","e":"television"},
    {"h":"电影","p":"diànyǐng","e":"movie, film"},
    {"h":"电影院","p":"diànyǐngyuàn","e":"cinema"},
    {"h":"东西","p":"dōngxi","e":"thing, object"},
    {"h":"都","p":"dōu","e":"all, both"},
    {"h":"读","p":"dú","e":"to read"},
    {"h":"读书","p":"dúshū","e":"to read a book"},
    {"h":"对","p":"duì","e":"correct, right"},
    {"h":"对不起","p":"duìbuqǐ","e":"sorry"},
    {"h":"多","p":"duō","e":"many, much"},
    {"h":"多少","p":"duōshao","e":"how many, how much"},
    {"h":"儿子","p":"érzi","e":"son"},
    {"h":"二","p":"èr","e":"two"},
    {"h":"饭","p":"fàn","e":"cooked rice, meal"},
    {"h":"饭店","p":"fàndiàn","e":"restaurant"},
    {"h":"房间","p":"fángjiān","e":"room"},
    {"h":"非常","p":"fēicháng","e":"very, extremely"},
    {"h":"飞机","p":"fēijī","e":"airplane"},
    {"h":"分","p":"fēn","e":"minute"},
    {"h":"分钟","p":"fēnzhōng","e":"minute"},
    {"h":"高兴","p":"gāoxìng","e":"happy, glad"},
    {"h":"歌","p":"gē","e":"song"},
    {"h":"哥哥","p":"gēge","e":"older brother"},
    {"h":"个","p":"gè","e":"measure word for general objects"},
    {"h":"给","p":"gěi","e":"to give"},
    {"h":"公司","p":"gōngsī","e":"company"},
    {"h":"工作","p":"gōngzuò","e":"work"},
    {"h":"狗","p":"gǒu","e":"dog"},
    {"h":"贵","p":"guì","e":"expensive"},
    {"h":"国","p":"guó","e":"country"},
    {"h":"还","p":"hái","e":"still, also"},
    {"h":"孩子","p":"háizi","e":"child"},
    {"h":"汉语","p":"Hànyǔ","e":"Chinese language"},
    {"h":"汉字","p":"Hànzì","e":"Chinese character"},
    {"h":"好","p":"hǎo","e":"good"},
    {"h":"好吃","p":"hǎochī","e":"delicious, tasty"},
    {"h":"好看","p":"hǎokàn","e":"good-looking"},
    {"h":"好听","p":"hǎotīng","e":"pleasant to listen to"},
    {"h":"好玩儿","p":"hǎowánr","e":"fun, amusing"},
    {"h":"号","p":"hào","e":"number"},
    {"h":"喝","p":"hē","e":"to drink"},
    {"h":"和","p":"hé","e":"and, with"},
    {"h":"很","p":"hěn","e":"very"},
    {"h":"后","p":"hòu","e":"behind, later"},
    {"h":"回","p":"huí","e":"to return"},
    {"h":"会","p":"huì","e":"can, to be able to"},
    {"h":"火车","p":"huǒchē","e":"train"},
    {"h":"鸡蛋","p":"jīdàn","e":"egg"},
    {"h":"几","p":"jǐ","e":"how many, a few"},
    {"h":"家","p":"jiā","e":"home, family"},
    {"h":"家人","p":"jiārén","e":"family member"},
    {"h":"见","p":"jiàn","e":"to see"},
    {"h":"件","p":"jiàn","e":"measure word for items"},
    {"h":"饺子","p":"jiǎozi","e":"dumpling"},
    {"h":"叫","p":"jiào","e":"to be called, to call"},
    {"h":"姐姐","p":"jiějie","e":"older sister"},
    {"h":"今年","p":"jīnnián","e":"this year"},
    {"h":"今天","p":"jīntiān","e":"today"},
    {"h":"九","p":"jiǔ","e":"nine"},
    {"h":"觉得","p":"juéde","e":"to feel, to think"},
    {"h":"开","p":"kāi","e":"to open"},
    {"h":"开车","p":"kāichē","e":"to drive"},
    {"h":"看","p":"kàn","e":"to see, to look"},
    {"h":"看病","p":"kànbìng","e":"to see a doctor"},
    {"h":"看见","p":"kànjiàn","e":"to see"},
    {"h":"可以","p":"kěyǐ","e":"can, may"},
    {"h":"课","p":"kè","e":"class, lesson"},
    {"h":"口","p":"kǒu","e":"mouth"},
    {"h":"块","p":"kuài","e":"measure word for pieces, chunks, money"},
    {"h":"来","p":"lái","e":"to come"},
    {"h":"老师","p":"lǎoshī","e":"teacher"},
    {"h":"了","p":"le","e":"particle indicating completed action"},
    {"h":"冷","p":"lěng","e":"cold"},
    {"h":"里","p":"lǐ","e":"inside, in, mile"},
    {"h":"两","p":"liǎng","e":"two"},
    {"h":"零","p":"líng","e":"zero"},
    {"h":"六","p":"liù","e":"six"},
    {"h":"妈妈","p":"māma","e":"mom"},
    {"h":"吗","p":"ma","e":"question particle"},
    {"h":"买","p":"mǎi","e":"to buy"},
    {"h":"卖","p":"mài","e":"to sell"},
    {"h":"忙","p":"máng","e":"busy"},
    {"h":"猫","p":"māo","e":"cat"},
    {"h":"没关系","p":"méi guānxi","e":"never mind, it's okay"},
    {"h":"没事","p":"méishì","e":"to have nothing to do"},
    {"h":"没有","p":"méiyǒu","e":"to not have"},
    {"h":"妹妹","p":"mèimei","e":"younger sister"},
    {"h":"们","p":"men","e":"plural suffix"},
    {"h":"米饭","p":"mǐfàn","e":"cooked rice"},
    {"h":"面包","p":"miànbāo","e":"bread"},
    {"h":"面条儿","p":"miàntiáor","e":"noodles"},
    {"h":"明年","p":"míngnián","e":"next year"},
    {"h":"明天","p":"míngtiān","e":"tomorrow"},
    {"h":"名字","p":"míngzi","e":"name"},
    {"h":"哪","p":"nǎ","e":"which"},
    {"h":"哪个","p":"nǎge","e":"which one"},
    {"h":"哪里","p":"nǎlǐ","e":"where"},
    {"h":"哪儿","p":"nǎr","e":"where"},
    {"h":"哪些","p":"nǎxiē","e":"which ones"},
    {"h":"那","p":"nà","e":"that"},
    {"h":"那边","p":"nàbiān","e":"over there"},
    {"h":"那个","p":"nàge","e":"that one"},
    {"h":"那里","p":"nàlǐ","e":"there"},
    {"h":"那儿","p":"nàr","e":"there"},
    {"h":"那些","p":"nàxiē","e":"those"},
    {"h":"男","p":"nán","e":"male"},
    {"h":"男朋友","p":"nánpéngyou","e":"boyfriend"},
    {"h":"呢","p":"ne","e":"question or continuation particle"},
    {"h":"能","p":"néng","e":"can, be able to"},
    {"h":"你","p":"nǐ","e":"you"},
    {"h":"你好","p":"nǐ hǎo","e":"hello"},
    {"h":"你们","p":"nǐmen","e":"you plural"},
    {"h":"年","p":"nián","e":"year"},
    {"h":"您","p":"nín","e":"you"},
    {"h":"牛奶","p":"niúnǎi","e":"milk"},
    {"h":"女","p":"nǚ","e":"female"},
    {"h":"女儿","p":"nǚ'ér","e":"daughter"},
    {"h":"女朋友","p":"nǚpéngyou","e":"girlfriend"},
    {"h":"女士","p":"nǚshì","e":"lady, Ms."},
    {"h":"朋友","p":"péngyou","e":"friend"},
    {"h":"便宜","p":"piányi","e":"cheap"},
    {"h":"漂亮","p":"piàoliang","e":"beautiful"},
    {"h":"苹果","p":"píngguǒ","e":"apple"},
    {"h":"七","p":"qī","e":"seven"},
    {"h":"起床","p":"qǐchuáng","e":"to get up"},
    {"h":"千","p":"qiān","e":"thousand"},
    {"h":"前","p":"qián","e":"front, before"},
    {"h":"钱","p":"qián","e":"money"},
    {"h":"请","p":"qǐng","e":"please"},
    {"h":"请问","p":"qǐngwèn","e":"may I ask"},
    {"h":"去","p":"qù","e":"to go"},
    {"h":"去年","p":"qùnián","e":"last year"},
    {"h":"热","p":"rè","e":"hot"},
    {"h":"人","p":"rén","e":"person"},
    {"h":"认识","p":"rènshi","e":"to know, to recognize"},
    {"h":"日","p":"rì","e":"measure word for days"},
    {"h":"三","p":"sān","e":"three"},
    {"h":"商店","p":"shāngdiàn","e":"store, shop"},
    {"h":"上","p":"shàng","e":"up, above"},
    {"h":"上班","p":"shàngbān","e":"to go to work"},
    {"h":"上课","p":"shàngkè","e":"to attend class"},
    {"h":"上午","p":"shàngwǔ","e":"morning"},
    {"h":"上学","p":"shàngxué","e":"to go to school"},
    {"h":"少","p":"shǎo","e":"few, little"},
    {"h":"谁","p":"shéi","e":"who"},
    {"h":"什么","p":"shénme","e":"what"},
    {"h":"生病","p":"shēngbìng","e":"to get sick"},
    {"h":"十","p":"shí","e":"ten"},
    {"h":"时候","p":"shíhou","e":"moment, time"},
    {"h":"时间","p":"shíjiān","e":"time"},
    {"h":"事","p":"shì","e":"matter, thing"},
    {"h":"是","p":"shì","e":"to be"},
    {"h":"手机","p":"shǒujī","e":"cell phone"},
    {"h":"书","p":"shū","e":"book"},
    {"h":"书店","p":"shūdiàn","e":"bookstore"},
    {"h":"水","p":"shuǐ","e":"water"},
    {"h":"水果","p":"shuǐguǒ","e":"fruit"},
    {"h":"睡","p":"shuì","e":"to sleep"},
    {"h":"睡觉","p":"shuìjiào","e":"to sleep"},
    {"h":"说","p":"shuō","e":"to speak, to say"},
    {"h":"说话","p":"shuōhuà","e":"to talk"},
    {"h":"四","p":"sì","e":"four"},
    {"h":"岁","p":"suì","e":"measure word for age"},
    {"h":"他","p":"tā","e":"he, him"},
    {"h":"它","p":"tā","e":"it"},
    {"h":"她","p":"tā","e":"she"},
    {"h":"他们","p":"tāmen","e":"they"},
    {"h":"它们","p":"tāmen","e":"they"},
    {"h":"她们","p":"tāmen","e":"they"},
    {"h":"太","p":"tài","e":"too, extremely"},
    {"h":"天","p":"tiān","e":"day"},
    {"h":"天气","p":"tiānqì","e":"weather"},
    {"h":"听","p":"tīng","e":"to listen"},
    {"h":"听见","p":"tīngjiàn","e":"to hear"},
    {"h":"同学","p":"tóngxué","e":"classmate"},
    {"h":"外","p":"wài","e":"outside, exterior"},
    {"h":"外边","p":"wàibian","e":"outside"},
    {"h":"玩","p":"wán","e":"to play"},
    {"h":"晚","p":"wǎn","e":"late"},
    {"h":"晚饭","p":"wǎnfàn","e":"dinner"},
    {"h":"晚上","p":"wǎnshang","e":"evening"},
    {"h":"喂","p":"wèi","e":"hello"},
    {"h":"问","p":"wèn","e":"to ask"},
    {"h":"问题","p":"wèntí","e":"question"},
    {"h":"我","p":"wǒ","e":"I"},
    {"h":"我们","p":"wǒmen","e":"we"},
    {"h":"五","p":"wǔ","e":"five"},
    {"h":"午饭","p":"wǔfàn","e":"lunch"},
    {"h":"喜欢","p":"xǐhuan","e":"to like"},
    {"h":"下","p":"xià","e":"down, below"},
    {"h":"下雨","p":"xià yǔ","e":"to rain"},
    {"h":"下班","p":"xiàbān","e":"to get off work"},
    {"h":"下课","p":"xiàkè","e":"to finish class"},
    {"h":"下午","p":"xiàwǔ","e":"afternoon"},
    {"h":"先生","p":"xiānsheng","e":"Mr., husband"},
    {"h":"现在","p":"xiànzài","e":"now"},
    {"h":"想","p":"xiǎng","e":"to think; to want"},
    {"h":"小","p":"xiǎo","e":"small"},
    {"h":"小朋友","p":"xiǎopéngyǒu","e":"little friend, child"},
    {"h":"小时","p":"xiǎoshí","e":"hour"},
    {"h":"小学","p":"xiǎoxué","e":"primary school"},
    {"h":"小学生","p":"xiǎoxuéshēng","e":"primary school student"},
    {"h":"些","p":"xiē","e":"measure word for indefinite amount"},
    {"h":"写","p":"xiě","e":"to write"},
    {"h":"谢谢","p":"xièxie","e":"to thank"},
    {"h":"新","p":"xīn","e":"new"},
    {"h":"星期","p":"xīngqī","e":"week"},
    {"h":"星期日","p":"xīngqīrì","e":"Sunday"},
    {"h":"星期天","p":"xīngqītiān","e":"Sunday"},
    {"h":"休息","p":"xiūxi","e":"to rest"},
    {"h":"学","p":"xué","e":"to learn, to study"},
    {"h":"学生","p":"xuéshēng","e":"student"},
    {"h":"学习","p":"xuéxí","e":"to study"},
    {"h":"学校","p":"xuéxiào","e":"school"},
    {"h":"雪","p":"xuě","e":"snow"},
    {"h":"要","p":"yào","e":"to want, to need"},
    {"h":"也","p":"yě","e":"also, too"},
    {"h":"一","p":"yī","e":"one"},
    {"h":"衣服","p":"yīfu","e":"clothes"},
    {"h":"医生","p":"yīshēng","e":"doctor"},
    {"h":"医院","p":"yīyuàn","e":"hospital"},
    {"h":"一半","p":"yíbàn","e":"half"},
    {"h":"一下","p":"yíxià","e":"once, a little"},
    {"h":"椅子","p":"yǐzi","e":"chair"},
    {"h":"一点儿","p":"yìdiǎnr","e":"a little, a bit"},
    {"h":"一些","p":"yìxiē","e":"some, a few"},
    {"h":"有","p":"yǒu","e":"to have, to exist"},
    {"h":"有的","p":"yǒude","e":"some of them"},
    {"h":"有点儿","p":"yǒudiǎnr","e":"a little, slightly"},
    {"h":"有些","p":"yǒuxiē","e":"some, some of"},
    {"h":"雨","p":"yǔ","e":"rain"},
    {"h":"元","p":"yuán","e":"yuan"},
    {"h":"月","p":"yuè","e":"month; moon"},
    {"h":"再","p":"zài","e":"again, then"},
    {"h":"在","p":"zài","e":"to be at; at; in the middle of"},
    {"h":"再见","p":"zàijiàn","e":"goodbye"},
    {"h":"早","p":"zǎo","e":"early"},
    {"h":"早饭","p":"zǎofàn","e":"breakfast"},
    {"h":"早上","p":"zǎoshang","e":"morning"},
    {"h":"怎么","p":"zěnme","e":"how"},
    {"h":"怎么样","p":"zěnmeyàng","e":"how about, what do you think"},
    {"h":"找","p":"zhǎo","e":"to look for"},
    {"h":"这","p":"zhè","e":"this"},
    {"h":"这边","p":"zhèbiān","e":"here"},
    {"h":"这个","p":"zhège","e":"this one"},
    {"h":"这里","p":"zhèlǐ","e":"here"},
    {"h":"这儿","p":"zhèr","e":"here"},
    {"h":"这些","p":"zhèxiē","e":"these"},
    {"h":"真","p":"zhēn","e":"really"},
    {"h":"正在","p":"zhèngzài","e":"in the process of"},
    {"h":"只","p":"zhī","e":"measure word for animals"},
    {"h":"知道","p":"zhīdào","e":"to know"},
    {"h":"中国","p":"Zhōngguó","e":"China"},
    {"h":"中文","p":"Zhōngwén","e":"Chinese language"},
    {"h":"中午","p":"zhōngwǔ","e":"noon"},
    {"h":"中学","p":"zhōngxué","e":"middle school"},
    {"h":"中学生","p":"zhōngxuéshēng","e":"middle school student"},
    {"h":"住","p":"zhù","e":"to live, to reside"},
    {"h":"桌子","p":"zhuōzi","e":"table, desk"},
    {"h":"字","p":"zì","e":"character, script"},
    {"h":"昨天","p":"zuótiān","e":"yesterday"},
    {"h":"坐","p":"zuò","e":"to sit"},
    {"h":"做","p":"zuò","e":"to do, to make"},
    {"h":"做饭","p":"zuò fàn","e":"to cook"}
  ],
  2: [
    {"h":"啊","p":"a","e":"ah, oh"},
    {"h":"爱好","p":"àihào","e":"to like; hobby"},
    {"h":"白色","p":"báisè","e":"white"},
    {"h":"班","p":"bān","e":"class, team"},
    {"h":"帮","p":"bāng","e":"to help"},
    {"h":"帮忙","p":"bāngmáng","e":"to help"},
    {"h":"包","p":"bāo","e":"to wrap, bag"},
    {"h":"本子","p":"běnzi","e":"notebook"},
    {"h":"比","p":"bǐ","e":"to compare; than"},
    {"h":"笔","p":"bǐ","e":"pen"},
    {"h":"别","p":"bié","e":"don't"},
    {"h":"不错","p":"búcuò","e":"not bad, pretty good"},
    {"h":"不好意思","p":"bù hǎoyìsi","e":"sorry, embarrassed"},
    {"h":"长","p":"cháng","e":"long"},
    {"h":"车站","p":"chēzhàn","e":"station"},
    {"h":"出","p":"chū","e":"to go out"},
    {"h":"出国","p":"chūguó","e":"to go abroad"},
    {"h":"出来","p":"chūlái","e":"to come out"},
    {"h":"出门","p":"chūmén","e":"to go out"},
    {"h":"出去","p":"chūqù","e":"to go out"},
    {"h":"床","p":"chuáng","e":"bed"},
    {"h":"词","p":"cí","e":"word, term"},
    {"h":"次","p":"cì","e":"measure word of time"},
    {"h":"从","p":"cóng","e":"from"},
    {"h":"从小","p":"cóngxiǎo","e":"from childhood"},
    {"h":"错","p":"cuò","e":"wrong, mistaken"},
    {"h":"打","p":"dǎ","e":"to hit, to play"},
    {"h":"打车","p":"dǎchē","e":"to take a taxi"},
    {"h":"打开","p":"dǎkāi","e":"to open"},
    {"h":"但","p":"dàn","e":"but, however"},
    {"h":"但是","p":"dànshì","e":"but, however"},
    {"h":"得","p":"de","e":"particle indicating degree"},
    {"h":"地","p":"de","e":"particle modifying adjective"},
    {"h":"等","p":"děng","e":"to wait"},
    {"h":"地铁","p":"dìtiě","e":"subway, metro"},
    {"h":"懂","p":"dǒng","e":"to understand"},
    {"h":"动","p":"dòng","e":"to move, to act"},
    {"h":"饭馆","p":"fànguǎn","e":"restaurant"},
    {"h":"飞","p":"fēi","e":"to fly"},
    {"h":"高","p":"gāo","e":"tall, high"},
    {"h":"高中","p":"gāozhōng","e":"high school"},
    {"h":"告诉","p":"gàosu","e":"to tell"},
    {"h":"个子","p":"gèzi","e":"height, stature"},
    {"h":"跟","p":"gēn","e":"with; and"},
    {"h":"公交车","p":"gōngjiāochē","e":"bus"},
    {"h":"过","p":"guò","e":"to pass"},
    {"h":"过来","p":"guòlái","e":"to come over"},
    {"h":"过年","p":"guònián","e":"to celebrate New Year"},
    {"h":"过去","p":"guòqù","e":"to go over"},
    {"h":"还是","p":"háishi","e":"still; or"},
    {"h":"黑色","p":"hēisè","e":"black"},
    {"h":"红茶","p":"hóngchá","e":"black tea"},
    {"h":"红色","p":"hóngsè","e":"red"},
    {"h":"后面","p":"hòumiàn","e":"behind, back"},
    {"h":"花","p":"huā","e":"to spend; flower"},
    {"h":"画","p":"huà","e":"to draw; painting"},
    {"h":"坏","p":"huài","e":"bad, broken"},
    {"h":"回来","p":"huílái","e":"to come back"},
    {"h":"回去","p":"huíqù","e":"to go back"},
    {"h":"机场","p":"jīchǎng","e":"airport"},
    {"h":"机票","p":"jīpiào","e":"airplane ticket"},
    {"h":"记得","p":"jìde","e":"to remember"},
    {"h":"间","p":"jiān","e":"measure word for rooms"},
    {"h":"教","p":"jiāo","e":"to teach"},
    {"h":"教室","p":"jiàoshì","e":"classroom"},
    {"h":"介绍","p":"jièshào","e":"to introduce"},
    {"h":"进","p":"jìn","e":"to enter"},
    {"h":"近","p":"jìn","e":"near, close"},
    {"h":"进来","p":"jìnlái","e":"to come in"},
    {"h":"进去","p":"jìnqù","e":"to go in"},
    {"h":"经常","p":"jīngcháng","e":"often"},
    {"h":"酒店","p":"jiǔdiàn","e":"hotel"},
    {"h":"就","p":"jiù","e":"just, then"},
    {"h":"咖啡","p":"kāfēi","e":"coffee"},
    {"h":"开始","p":"kāishǐ","e":"to start"},
    {"h":"开学","p":"kāixué","e":"school starts"},
    {"h":"考","p":"kǎo","e":"to test"},
    {"h":"考试","p":"kǎoshì","e":"exam"},
    {"h":"可能","p":"kěnéng","e":"possible; may"},
    {"h":"裤子","p":"kùzi","e":"pants"},
    {"h":"快","p":"kuài","e":"fast; soon"},
    {"h":"快乐","p":"kuàilè","e":"happy, joyful"},
    {"h":"快要","p":"kuàiyào","e":"soon, almost"},
    {"h":"篮球","p":"lánqiú","e":"basketball"},
    {"h":"累","p":"lèi","e":"tired"},
    {"h":"离","p":"lí","e":"to leave, away from"},
    {"h":"里面","p":"lǐmiàn","e":"inside"},
    {"h":"楼","p":"lóu","e":"building, floor"},
    {"h":"路","p":"lù","e":"road, path"},
    {"h":"路上","p":"lùshang","e":"on the road"},
    {"h":"旅游","p":"lǚyóu","e":"to travel"},
    {"h":"绿茶","p":"lǜchá","e":"green tea"},
    {"h":"绿色","p":"lǜsè","e":"green color"},
    {"h":"慢","p":"màn","e":"slow"},
    {"h":"没意思","p":"méi yìsi","e":"boring"},
    {"h":"每","p":"měi","e":"every, each"},
    {"h":"门","p":"mén","e":"door, gate"},
    {"h":"门口","p":"ménkǒu","e":"doorway, entrance"},
    {"h":"门票","p":"ménpiào","e":"ticket"},
    {"h":"面","p":"miàn","e":"side, aspect"},
    {"h":"名","p":"míng","e":"name; measure word"},
    {"h":"拿","p":"ná","e":"to take, to hold"},
    {"h":"那么","p":"nàme","e":"so, like that"},
    {"h":"那样","p":"nàyàng","e":"like that"},
    {"h":"奶茶","p":"nǎichá","e":"milk tea"},
    {"h":"奶奶","p":"nǎinai","e":"grandmother"},
    {"h":"男孩儿","p":"nánháir","e":"boy"},
    {"h":"鸟","p":"niǎo","e":"bird"},
    {"h":"女孩儿","p":"nǚháir","e":"girl"},
    {"h":"旁边","p":"pángbiān","e":"side"},
    {"h":"跑","p":"pǎo","e":"to run"},
    {"h":"跑步","p":"pǎobù","e":"to run, jogging"},
    {"h":"票","p":"piào","e":"ticket"},
    {"h":"妻子","p":"qīzi","e":"wife"},
    {"h":"起来","p":"qǐlái","e":"to get up"},
    {"h":"前面","p":"qiánmiàn","e":"front"},
    {"h":"晴","p":"qíng","e":"sunny, clear"},
    {"h":"球","p":"qiú","e":"ball, sphere"},
    {"h":"让","p":"ràng","e":"to let, to allow"},
    {"h":"肉","p":"ròu","e":"meat"},
    {"h":"商场","p":"shāngchǎng","e":"shopping mall"},
    {"h":"上来","p":"shànglái","e":"to come up"},
    {"h":"上面","p":"shàngmiàn","e":"above, top"},
    {"h":"上去","p":"shàngqù","e":"to go up"},
    {"h":"上网","p":"shàngwǎng","e":"to go online"},
    {"h":"身体","p":"shēntǐ","e":"body"},
    {"h":"生日","p":"shēngrì","e":"birthday"},
    {"h":"时","p":"shí","e":"time, moment"},
    {"h":"事情","p":"shìqing","e":"matter, affair"},
    {"h":"手","p":"shǒu","e":"hand"},
    {"h":"手表","p":"shǒubiǎo","e":"watch"},
    {"h":"书包","p":"shūbāo","e":"backpack"},
    {"h":"舒服","p":"shūfu","e":"comfortable"},
    {"h":"送","p":"sòng","e":"to give, to send"},
    {"h":"虽然","p":"suīrán","e":"although"},
    {"h":"所以","p":"suǒyǐ","e":"so, therefore"},
    {"h":"疼","p":"téng","e":"painful, sore"},
    {"h":"踢","p":"tī","e":"to kick"},
    {"h":"题","p":"tí","e":"question, problem"},
    {"h":"条","p":"tiáo","e":"measure word for long things"},
    {"h":"跳舞","p":"tiàowǔ","e":"to dance"},
    {"h":"头","p":"tóu","e":"head"},
    {"h":"外国","p":"wàiguó","e":"foreign country"},
    {"h":"外面","p":"wàimiàn","e":"outside"},
    {"h":"完","p":"wán","e":"to finish"},
    {"h":"万","p":"wàn","e":"ten thousand"},
    {"h":"往","p":"wǎng","e":"toward"},
    {"h":"网上","p":"wǎngshang","e":"online"},
    {"h":"忘","p":"wàng","e":"to forget"},
    {"h":"位","p":"wèi","e":"measure word for people"},
    {"h":"为什么","p":"wèi shénme","e":"why"},
    {"h":"希望","p":"xīwàng","e":"to hope"},
    {"h":"洗","p":"xǐ","e":"to wash"},
    {"h":"洗手间","p":"xǐshǒujiān","e":"restroom"},
    {"h":"下来","p":"xiàlái","e":"to come down"},
    {"h":"下面","p":"xiàmiàn","e":"below, under"},
    {"h":"下去","p":"xiàqù","e":"to go down"},
    {"h":"小孩儿","p":"xiǎoháir","e":"child"},
    {"h":"小时候","p":"xiǎoshíhou","e":"childhood"},
    {"h":"笑","p":"xiào","e":"to laugh, to smile"},
    {"h":"姓","p":"xìng","e":"surname"},
    {"h":"姓名","p":"xìngmíng","e":"full name"},
    {"h":"颜色","p":"yánsè","e":"color"},
    {"h":"眼睛","p":"yǎnjing","e":"eye"},
    {"h":"药","p":"yào","e":"medicine"},
    {"h":"药店","p":"yàodiàn","e":"pharmacy"},
    {"h":"爷爷","p":"yéye","e":"grandfather"},
    {"h":"一会儿","p":"yíhuìr","e":"a while, a moment"},
    {"h":"已经","p":"yǐjīng","e":"already"},
    {"h":"一起","p":"yìqǐ","e":"together"},
    {"h":"意思","p":"yìsi","e":"meaning, idea"},
    {"h":"阴","p":"yīn","e":"cloudy"},
    {"h":"因为","p":"yīnwèi","e":"because"},
    {"h":"游","p":"yóu","e":"to swim"},
    {"h":"游泳","p":"yóuyǒng","e":"to swim"},
    {"h":"有意思","p":"yǒu yìsi","e":"interesting"},
    {"h":"有时","p":"yǒushí","e":"sometimes"},
    {"h":"右","p":"yòu","e":"right"},
    {"h":"右边","p":"yòubian","e":"right side"},
    {"h":"鱼","p":"yú","e":"fish"},
    {"h":"远","p":"yuǎn","e":"far"},
    {"h":"运动","p":"yùndòng","e":"to exercise; sports"},
    {"h":"站","p":"zhàn","e":"station; to stand"},
    {"h":"丈夫","p":"zhàngfu","e":"husband"},
    {"h":"这么","p":"zhème","e":"so, such"},
    {"h":"这样","p":"zhèyàng","e":"like this, so"},
    {"h":"着","p":"zhe","e":"particle indicating ongoing action"},
    {"h":"正","p":"zhèng","e":"just, exactly"},
    {"h":"周","p":"zhōu","e":"week"},
    {"h":"准备","p":"zhǔnbèi","e":"to prepare"},
    {"h":"自己","p":"zìjǐ","e":"oneself"},
    {"h":"走","p":"zǒu","e":"to walk"},
    {"h":"走路","p":"zǒulù","e":"to walk"},
    {"h":"足球","p":"zúqiú","e":"soccer, football"},
    {"h":"最","p":"zuì","e":"most, -est"},
    {"h":"左","p":"zuǒ","e":"left"},
    {"h":"左边","p":"zuǒbian","e":"left side"}
  ],
  3: [
    {"h":"阿姨","p":"āyí","e":"aunt"},
    {"h":"矮","p":"ǎi","e":"short"},
    {"h":"爱人","p":"àiren","e":"spouse"},
    {"h":"安静","p":"ānjìng","e":"quiet"},
    {"h":"安全","p":"ānquán","e":"safe"},
    {"h":"把","p":"bǎ","e":"measure word; particle"},
    {"h":"搬","p":"bān","e":"to move, to carry"},
    {"h":"班级","p":"bānjí","e":"class, grade"},
    {"h":"搬家","p":"bānjiā","e":"to move house"},
    {"h":"办","p":"bàn","e":"to do, to handle"},
    {"h":"办法","p":"bànfǎ","e":"way, solution"},
    {"h":"办公室","p":"bàngōngshì","e":"office"},
    {"h":"半天","p":"bàntiān","e":"half a day"},
    {"h":"帮助","p":"bāngzhù","e":"help"},
    {"h":"饱","p":"bǎo","e":"full"},
    {"h":"报纸","p":"bàozhǐ","e":"newspaper"},
    {"h":"北","p":"běi","e":"north"},
    {"h":"北方","p":"běifāng","e":"north"},
    {"h":"被","p":"bèi","e":"by"},
    {"h":"笔记","p":"bǐjì","e":"notes"},
    {"h":"比较","p":"bǐjiào","e":"to compare; quite"},
    {"h":"笔记本","p":"bǐjìběn","e":"notebook"},
    {"h":"比如","p":"bǐrú","e":"for example"},
    {"h":"比赛","p":"bǐsài","e":"to compete; game"},
    {"h":"必须","p":"bìxū","e":"must"},
    {"h":"变","p":"biàn","e":"to change"},
    {"h":"遍","p":"biàn","e":"measure word for actions"},
    {"h":"变成","p":"biànchéng","e":"to become"},
    {"h":"变化","p":"biànhuà","e":"to change; change"},
    {"h":"表演","p":"biǎoyǎn","e":"to perform"},
    {"h":"别的","p":"biéde","e":"other"},
    {"h":"别人","p":"biérén","e":"other people"},
    {"h":"宾馆","p":"bīnguǎn","e":"hotel"},
    {"h":"冰","p":"bīng","e":"ice"},
    {"h":"冰激凌","p":"bīngjīlíng","e":"ice cream"},
    {"h":"冰箱","p":"bīngxiāng","e":"refrigerator"},
    {"h":"病人","p":"bìngrén","e":"patient"},
    {"h":"不但","p":"búdàn","e":"not only"},
    {"h":"不见","p":"bújiàn","e":"to disappear"},
    {"h":"不用","p":"búyòng","e":"need not"},
    {"h":"不同","p":"bù tóng","e":"different"},
    {"h":"不久","p":"bùjiǔ","e":"soon"},
    {"h":"不行","p":"bùxíng","e":"not allowed"},
    {"h":"才","p":"cái","e":"just, only"},
    {"h":"菜单","p":"càidān","e":"menu"},
    {"h":"参加","p":"cānjiā","e":"to join, to attend"},
    {"h":"草","p":"cǎo","e":"grass"},
    {"h":"草地","p":"cǎodì","e":"grassland"},
    {"h":"层","p":"céng","e":"measure word for floors"},
    {"h":"查","p":"chá","e":"to check"},
    {"h":"差","p":"chà","e":"bad, poor"},
    {"h":"差不多","p":"chàbuduō","e":"almost, similar"},
    {"h":"尝","p":"cháng","e":"to taste"},
    {"h":"常","p":"cháng","e":"often"},
    {"h":"常见","p":"cháng jiàn","e":"common"},
    {"h":"常用","p":"cháng yòng","e":"commonly used"},
    {"h":"常常","p":"chángcháng","e":"often"},
    {"h":"衬衫","p":"chènshān","e":"shirt"},
    {"h":"成绩","p":"chéngjì","e":"score, grade"},
    {"h":"城市","p":"chéngshì","e":"city"},
    {"h":"迟到","p":"chídào","e":"to be late"},
    {"h":"出发","p":"chūfā","e":"to set out"},
    {"h":"出生","p":"chūshēng","e":"to be born"},
    {"h":"出院","p":"chūyuàn","e":"to be discharged"},
    {"h":"初中","p":"chūzhōng","e":"junior high school"},
    {"h":"除了","p":"chúle","e":"except, besides"},
    {"h":"船","p":"chuán","e":"boat"},
    {"h":"春天","p":"chūntiān","e":"spring"},
    {"h":"词典","p":"cídiǎn","e":"dictionary"},
    {"h":"聪明","p":"cōngmíng","e":"smart, clever"},
    {"h":"打扫","p":"dǎsǎo","e":"to clean"},
    {"h":"打算","p":"dǎsuàn","e":"to plan; plan"},
    {"h":"大概","p":"dàgài","e":"probably"},
    {"h":"大人","p":"dàren","e":"adult"},
    {"h":"大小","p":"dàxiǎo","e":"size"},
    {"h":"大熊猫","p":"dàxióngmāo","e":"giant panda"},
    {"h":"大衣","p":"dàyī","e":"coat"},
    {"h":"带","p":"dài","e":"to bring, to take"},
    {"h":"担心","p":"dānxīn","e":"to worry"},
    {"h":"蛋糕","p":"dàngāo","e":"cake"},
    {"h":"当然","p":"dāngrán","e":"of course"},
    {"h":"到处","p":"dàochù","e":"everywhere"},
    {"h":"得","p":"dé","e":"to get, to obtain"},
    {"h":"得到","p":"dédào","e":"to get"},
    {"h":"得分","p":"défēn","e":"to score"},
    {"h":"的话","p":"dehuà","e":"if"},
    {"h":"得","p":"děi","e":"must, need"},
    {"h":"灯","p":"dēng","e":"lamp, light"},
    {"h":"地","p":"dì","e":"ground, earth"},
    {"h":"地点","p":"dìdiǎn","e":"place, location"},
    {"h":"地方","p":"dìfang","e":"place"},
    {"h":"地图","p":"dìtú","e":"map"},
    {"h":"电","p":"diàn","e":"electricity"},
    {"h":"电梯","p":"diàntī","e":"elevator"},
    {"h":"电子书","p":"diànzǐshū","e":"e-book"},
    {"h":"丢","p":"diū","e":"to lose, to throw"},
    {"h":"东","p":"dōng","e":"east"},
    {"h":"东北","p":"dōngběi","e":"northeast"},
    {"h":"东方","p":"dōngfāng","e":"east"},
    {"h":"东南","p":"dōngnán","e":"southeast"},
    {"h":"冬天","p":"dōngtiān","e":"winter"},
    {"h":"懂得","p":"dǒngde","e":"to understand"},
    {"h":"动物","p":"dòngwù","e":"animal"},
    {"h":"动物园","p":"dòngwùyuán","e":"zoo"},
    {"h":"短","p":"duǎn","e":"short"},
    {"h":"短裤","p":"duǎnkù","e":"shorts"},
    {"h":"段","p":"duàn","e":"measure word for segment"},
    {"h":"锻炼","p":"duànliàn","e":"to exercise"},
    {"h":"对话","p":"duìhuà","e":"dialogue"},
    {"h":"饿","p":"è","e":"hungry"},
    {"h":"而且","p":"érqiě","e":"and, moreover"},
    {"h":"耳朵","p":"ěrduo","e":"ear"},
    {"h":"耳机","p":"ěrjī","e":"earphone"},
    {"h":"发","p":"fā","e":"to send, to issue"},
    {"h":"发烧","p":"fāshāo","e":"to have a fever"},
    {"h":"发生","p":"fāshēng","e":"to happen"},
    {"h":"发现","p":"fāxiàn","e":"to find, to discover"},
    {"h":"发展","p":"fāzhǎn","e":"to develop"},
    {"h":"方便","p":"fāngbiàn","e":"convenient"},
    {"h":"方便面","p":"fāngbiànmiàn","e":"instant noodles"},
    {"h":"方法","p":"fāngfǎ","e":"method"},
    {"h":"方向","p":"fāngxiàng","e":"direction"},
    {"h":"房子","p":"fángzi","e":"house"},
    {"h":"放","p":"fàng","e":"to put, to place"},
    {"h":"放假","p":"fàngjià","e":"to have a holiday"},
    {"h":"放心","p":"fàngxīn","e":"to relax"},
    {"h":"放学","p":"fàngxué","e":"school is over"},
    {"h":"分开","p":"fēnkāi","e":"to separate"},
    {"h":"风","p":"fēng","e":"wind"},
    {"h":"封","p":"fēng","e":"measure word for letters"},
    {"h":"夫妻","p":"fūqī","e":"husband and wife"},
    {"h":"服务","p":"fúwù","e":"to serve"},
    {"h":"附近","p":"fùjìn","e":"nearby"},
    {"h":"复习","p":"fùxí","e":"to review"},
    {"h":"该","p":"gāi","e":"should"},
    {"h":"干净","p":"gānjìng","e":"clean"},
    {"h":"感兴趣","p":"gǎn xìngqù","e":"to be interested in"},
    {"h":"感到","p":"gǎndào","e":"to feel"},
    {"h":"感冒","p":"gǎnmào","e":"cold; to catch a cold"},
    {"h":"干","p":"gàn","e":"to do, to work"},
    {"h":"刚","p":"gāng","e":"just, just now"},
    {"h":"刚才","p":"gāngcái","e":"just now"},
    {"h":"刚刚","p":"gānggāng","e":"just now"},
    {"h":"高铁","p":"gāotiě","e":"high-speed rail"},
    {"h":"根据","p":"gēnjù","e":"according to"},
    {"h":"更","p":"gèng","e":"more"},
    {"h":"公斤","p":"gōngjīn","e":"kilogram"},
    {"h":"公园","p":"gōngyuán","e":"park"},
    {"h":"工作日","p":"gōngzuòrì","e":"workday"},
    {"h":"故事","p":"gùshi","e":"story"},
    {"h":"刮","p":"guā","e":"to scrape, to blow"},
    {"h":"关","p":"guān","e":"to close"},
    {"h":"关机","p":"guānjī","e":"to turn off"},
    {"h":"关系","p":"guānxì","e":"relationship"},
    {"h":"关心","p":"guānxīn","e":"to care about"},
    {"h":"关于","p":"guānyú","e":"about, regarding"},
    {"h":"关注","p":"guānzhù","e":"to pay attention to"},
    {"h":"国家","p":"guójiā","e":"country"},
    {"h":"过节","p":"guòjié","e":"to celebrate a festival"},
    {"h":"过去","p":"guòqù","e":"past"},
    {"h":"海","p":"hǎi","e":"sea"},
    {"h":"害怕","p":"hàipà","e":"to be afraid"},
    {"h":"好多","p":"hǎoduō","e":"many, a lot"},
    {"h":"好久","p":"hǎojiǔ","e":"a long time"},
    {"h":"好像","p":"hǎoxiàng","e":"to seem, as if"},
    {"h":"号码","p":"hàomǎ","e":"number, code"},
    {"h":"河","p":"hé","e":"river"},
    {"h":"合适","p":"héshì","e":"suitable"},
    {"h":"黑板","p":"hēibǎn","e":"blackboard"},
    {"h":"红绿灯","p":"hóng-lǜdēng","e":"traffic light"},
    {"h":"后来","p":"hòulái","e":"later, afterwards"},
    {"h":"后年","p":"hòunián","e":"the year after next"},
    {"h":"后天","p":"hòutiān","e":"the day after tomorrow"},
    {"h":"护照","p":"hùzhào","e":"passport"},
    {"h":"花园","p":"huāyuán","e":"garden"},
    {"h":"画家","p":"huàjiā","e":"painter, artist"},
    {"h":"欢迎","p":"huānyíng","e":"to welcome"},
    {"h":"还","p":"huán","e":"to return, to give back"},
    {"h":"环境","p":"huánjìng","e":"environment"},
    {"h":"换","p":"huàn","e":"to exchange"},
    {"h":"黄色","p":"huángsè","e":"yellow"},
    {"h":"回答","p":"huídá","e":"to answer"},
    {"h":"会","p":"huì","e":"meeting"},
    {"h":"会议","p":"huìyì","e":"meeting"},
    {"h":"或","p":"huò","e":"or"},
    {"h":"或者","p":"huòzhě","e":"or"},
    {"h":"鸡","p":"jī","e":"chicken"},
    {"h":"几乎","p":"jīhū","e":"almost"},
    {"h":"机会","p":"jīhuì","e":"opportunity"},
    {"h":"极","p":"jí","e":"extremely"},
    {"h":"急","p":"jí","e":"urgent"},
    {"h":"记","p":"jì","e":"to remember"},
    {"h":"季","p":"jì","e":"season"},
    {"h":"季节","p":"jìjié","e":"season"},
    {"h":"加","p":"jiā","e":"to add"},
    {"h":"假期","p":"jiàqī","e":"vacation"},
    {"h":"坚持","p":"jiānchí","e":"to persist"},
    {"h":"检查","p":"jiǎnchá","e":"to check"},
    {"h":"简单","p":"jiǎndān","e":"simple"},
    {"h":"检票","p":"jiǎnpiào","e":"ticket checking"},
    {"h":"健康","p":"jiànkāng","e":"healthy"},
    {"h":"见面","p":"jiànmiàn","e":"to meet"},
    {"h":"讲","p":"jiǎng","e":"to speak"},
    {"h":"角","p":"jiǎo","e":"measure word; angle"},
    {"h":"脚","p":"jiǎo","e":"foot"},
    {"h":"接","p":"jiē","e":"to pick up, to receive"},
    {"h":"街","p":"jiē","e":"street"},
    {"h":"节","p":"jié","e":"measure word; festival"},
    {"h":"结婚","p":"jiéhūn","e":"to marry"},
    {"h":"节目","p":"jiémù","e":"program"},
    {"h":"节日","p":"jiérì","e":"festival"},
    {"h":"结束","p":"jiéshù","e":"to end"},
    {"h":"解决","p":"jiějué","e":"to solve"},
    {"h":"姐妹","p":"jiěmèi","e":"sister"},
    {"h":"借","p":"jiè","e":"to borrow"},
    {"h":"斤","p":"jīn","e":"catty"},
    {"h":"经过","p":"jīngguò","e":"to pass; process"},
    {"h":"经理","p":"jīnglǐ","e":"manager"},
    {"h":"久","p":"jiǔ","e":"long"},
    {"h":"酒","p":"jiǔ","e":"alcohol"},
    {"h":"旧","p":"jiù","e":"old"},
    {"h":"句","p":"jù","e":"measure word of sentence"},
    {"h":"句子","p":"jùzi","e":"sentence"},
    {"h":"决定","p":"juédìng","e":"to decide; decision"},
    {"h":"卡","p":"kǎ","e":"card"},
    {"h":"开花","p":"kāihuā","e":"to bloom"},
    {"h":"开会","p":"kāihuì","e":"to have a meeting"},
    {"h":"开机","p":"kāijī","e":"to turn on"},
    {"h":"开心","p":"kāixīn","e":"happy"},
    {"h":"看来","p":"kànlái","e":"it seems"},
    {"h":"可","p":"kě","e":"but"},
    {"h":"渴","p":"kě","e":"thirsty"},
    {"h":"可爱","p":"kě'ài","e":"lovely"},
    {"h":"可是","p":"kěshì","e":"but"},
    {"h":"刻","p":"kè","e":"quarter; to carve"},
    {"h":"课本","p":"kèběn","e":"textbook"},
    {"h":"客人","p":"kèrén","e":"guest"},
    {"h":"课文","p":"kèwén","e":"text"},
    {"h":"空调","p":"kōngtiáo","e":"air conditioner"},
    {"h":"哭","p":"kū","e":"to cry"},
    {"h":"筷子","p":"kuàizi","e":"chopsticks"},
    {"h":"矿泉水","p":"kuàngquánshuǐ","e":"mineral water"},
    {"h":"来自","p":"láizì","e":"to come from"},
    {"h":"蓝","p":"lán","e":"blue"},
    {"h":"老","p":"lǎo","e":"old, aged"},
    {"h":"老人","p":"lǎorén","e":"elderly person"},
    {"h":"离开","p":"líkāi","e":"to leave"},
    {"h":"礼物","p":"lǐwù","e":"gift"},
    {"h":"历史","p":"lìshǐ","e":"history"},
    {"h":"脸","p":"liǎn","e":"face"},
    {"h":"练","p":"liàn","e":"to practice"},
    {"h":"练习","p":"liànxí","e":"to practice; exercise"},
    {"h":"凉快","p":"liángkuai","e":"cool"},
    {"h":"辆","p":"liàng","e":"measure word for vehicles"},
    {"h":"聊","p":"liáo","e":"to chat"},
    {"h":"聊天儿","p":"liáotiānr","e":"to chat"},
    {"h":"了解","p":"liǎojiě","e":"to understand"},
    {"h":"邻居","p":"línjū","e":"neighbor"},
    {"h":"留学","p":"liúxué","e":"to study abroad"},
    {"h":"留学生","p":"liúxuéshēng","e":"overseas student"},
    {"h":"楼梯","p":"lóutī","e":"stairs"},
    {"h":"路边","p":"lùbiān","e":"roadside"},
    {"h":"路口","p":"lùkǒu","e":"intersection"},
    {"h":"马","p":"mǎ","e":"horse"},
    {"h":"马路","p":"mǎlù","e":"road"},
    {"h":"马上","p":"mǎshàng","e":"immediately"},
    {"h":"满意","p":"mǎnyì","e":"satisfied"},
    {"h":"毛","p":"máo","e":"measure word for money"},
    {"h":"米","p":"mǐ","e":"meter"},
    {"h":"面前","p":"miànqián","e":"in front of"},
    {"h":"明白","p":"míngbai","e":"to understand; clear"},
    {"h":"名单","p":"míngdān","e":"name list"},
    {"h":"名人","p":"míngrén","e":"famous person"},
    {"h":"南","p":"nán","e":"south"},
    {"h":"难","p":"nán","e":"difficult"},
    {"h":"南方","p":"nánfāng","e":"south"},
    {"h":"难过","p":"nánguò","e":"sad"},
    {"h":"难看","p":"nánkàn","e":"ugly"},
    {"h":"男人","p":"nánrén","e":"man"},
    {"h":"男生","p":"nánshēng","e":"boy student"},
    {"h":"难题","p":"nántí","e":"difficult problem"},
    {"h":"难听","p":"nántīng","e":"unpleasant to hear"},
    {"h":"年级","p":"niánjí","e":"grade"},
    {"h":"年轻","p":"niánqīng","e":"young"},
    {"h":"牛","p":"niú","e":"cow"},
    {"h":"努力","p":"nǔlì","e":"to work hard"},
    {"h":"女人","p":"nǚrén","e":"woman"},
    {"h":"女生","p":"nǚshēng","e":"girl student"},
    {"h":"爬","p":"pá","e":"to climb"},
    {"h":"怕","p":"pà","e":"to fear"},
    {"h":"拍照","p":"pāizhào","e":"to take a photo"},
    {"h":"盘子","p":"pánzi","e":"plate"},
    {"h":"胖","p":"pàng","e":"fat"},
    {"h":"啤酒","p":"píjiǔ","e":"beer"},
    {"h":"平时","p":"píngshí","e":"usually"},
    {"h":"瓶子","p":"píngzi","e":"bottle"},
    {"h":"骑","p":"qí","e":"to ride"},
    {"h":"奇怪","p":"qíguài","e":"strange"},
    {"h":"其实","p":"qíshí","e":"actually"},
    {"h":"其他","p":"qítā","e":"other"},
    {"h":"起","p":"qǐ","e":"to rise, to get up"},
    {"h":"起飞","p":"qǐfēi","e":"to take off"},
    {"h":"汽车","p":"qìchē","e":"car"},
    {"h":"铅笔","p":"qiānbǐ","e":"pencil"},
    {"h":"前年","p":"qiánnián","e":"year before last"},
    {"h":"前天","p":"qiántiān","e":"day before yesterday"},
    {"h":"清楚","p":"qīngchu","e":"clear, obvious"},
    {"h":"请假","p":"qǐngjià","e":"to ask for leave"},
    {"h":"请客","p":"qǐngkè","e":"to treat someone"},
    {"h":"秋天","p":"qiūtiān","e":"autumn"},
    {"h":"球场","p":"qiúchǎng","e":"sports field"},
    {"h":"裙子","p":"qúnzi","e":"skirt"},
    {"h":"然后","p":"ránhòu","e":"then, afterwards"},
    {"h":"热情","p":"rèqíng","e":"enthusiastic"},
    {"h":"认得","p":"rènde","e":"to recognize"},
    {"h":"认为","p":"rènwéi","e":"to think"},
    {"h":"认真","p":"rènzhēn","e":"serious, earnest"},
    {"h":"容易","p":"róngyì","e":"easy"},
    {"h":"如果","p":"rúguǒ","e":"if"},
    {"h":"伞","p":"sǎn","e":"umbrella"},
    {"h":"扫","p":"sǎo","e":"to sweep"},
    {"h":"沙发","p":"shāfā","e":"sofa"},
    {"h":"山","p":"shān","e":"mountain"},
    {"h":"上衣","p":"shàngyī","e":"jacket, top"},
    {"h":"勺子","p":"sháozi","e":"spoon"},
    {"h":"身边","p":"shēnbiān","e":"by one's side"},
    {"h":"身高","p":"shēngāo","e":"height"},
    {"h":"声","p":"shēng","e":"sound, voice"},
    {"h":"生活","p":"shēnghuó","e":"life; to live"},
    {"h":"生气","p":"shēngqì","e":"to get angry"},
    {"h":"声音","p":"shēngyīn","e":"sound"},
    {"h":"市","p":"shì","e":"city"},
    {"h":"试","p":"shì","e":"to try"},
    {"h":"室","p":"shì","e":"room"},
    {"h":"世界","p":"shìjiè","e":"world"},
    {"h":"收","p":"shōu","e":"to receive"},
    {"h":"收到","p":"shōudào","e":"to receive"},
    {"h":"受","p":"shòu","e":"to receive"},
    {"h":"瘦","p":"shòu","e":"thin, slim"},
    {"h":"受到","p":"shòudào","e":"to receive"},
    {"h":"叔叔","p":"shūshu","e":"uncle"},
    {"h":"树","p":"shù","e":"tree"},
    {"h":"数学","p":"shùxué","e":"mathematics"},
    {"h":"刷","p":"shuā","e":"to brush"},
    {"h":"双","p":"shuāng","e":"pair"},
    {"h":"水平","p":"shuǐpíng","e":"level, standard"},
    {"h":"司机","p":"sījī","e":"driver"},
    {"h":"四季","p":"sìjì","e":"four seasons"},
    {"h":"太阳","p":"tàiyáng","e":"sun"},
    {"h":"糖","p":"táng","e":"candy, sugar"},
    {"h":"特别","p":"tèbié","e":"special; particularly"},
    {"h":"提高","p":"tígāo","e":"to raise, to improve"},
    {"h":"体育","p":"tǐyù","e":"physical education"},
    {"h":"体育馆","p":"tǐyùguǎn","e":"gymnasium"},
    {"h":"甜","p":"tián","e":"sweet"},
    {"h":"跳","p":"tiào","e":"to jump"},
    {"h":"听说","p":"tīngshuō","e":"to hear said"},
    {"h":"挺","p":"tǐng","e":"quite, rather"},
    {"h":"同事","p":"tóngshì","e":"colleague"},
    {"h":"同意","p":"tóngyì","e":"to agree"},
    {"h":"头发","p":"tóufa","e":"hair"},
    {"h":"突然","p":"tūrán","e":"sudden"},
    {"h":"图书馆","p":"túshūguǎn","e":"library"},
    {"h":"腿","p":"tuǐ","e":"leg"},
    {"h":"外地","p":"wàidì","e":"other place"},
    {"h":"外卖","p":"wàimài","e":"takeaway"},
    {"h":"外语","p":"wàiyǔ","e":"foreign language"},
    {"h":"完成","p":"wánchéng","e":"to complete"},
    {"h":"碗","p":"wǎn","e":"bowl"},
    {"h":"晚点","p":"wǎndiǎn","e":"to be late"},
    {"h":"晚会","p":"wǎnhuì","e":"evening party"},
    {"h":"网球","p":"wǎngqiú","e":"tennis"},
    {"h":"网站","p":"wǎngzhàn","e":"website"},
    {"h":"忘记","p":"wàngjì","e":"to forget"},
    {"h":"为","p":"wèi","e":"for, because of"},
    {"h":"为了","p":"wèile","e":"in order to"},
    {"h":"卫生间","p":"wèishēngjiān","e":"bathroom"},
    {"h":"文化","p":"wénhuà","e":"culture"},
    {"h":"屋子","p":"wūzi","e":"room, house"},
    {"h":"西","p":"xī","e":"west"},
    {"h":"西北","p":"xīběi","e":"northwest"},
    {"h":"西方","p":"xīfāng","e":"west"},
    {"h":"西瓜","p":"xīguā","e":"watermelon"},
    {"h":"西南","p":"xīnán","e":"southwest"},
    {"h":"习惯","p":"xíguàn","e":"habit; to be used to"},
    {"h":"喜爱","p":"xǐ'ài","e":"to like, to love"},
    {"h":"洗衣机","p":"xǐyījī","e":"washing machine"},
    {"h":"洗澡","p":"xǐzǎo","e":"to take a bath"},
    {"h":"夏天","p":"xiàtiān","e":"summer"},
    {"h":"先","p":"xiān","e":"first, before"},
    {"h":"香蕉","p":"xiāngjiāo","e":"banana"},
    {"h":"相信","p":"xiāngxìn","e":"to believe"},
    {"h":"箱子","p":"xiāngzi","e":"box, case"},
    {"h":"向","p":"xiàng","e":"toward, to"},
    {"h":"像","p":"xiàng","e":"to resemble, to be like"},
    {"h":"相机","p":"xiàngjī","e":"camera"},
    {"h":"小区","p":"xiǎoqū","e":"residential community"},
    {"h":"小心","p":"xiǎoxīn","e":"to be careful"},
    {"h":"校园","p":"xiàoyuán","e":"campus"},
    {"h":"校长","p":"xiàozhǎng","e":"principal"},
    {"h":"鞋","p":"xié","e":"shoe"},
    {"h":"心里","p":"xīnlǐ","e":"heart, mind"},
    {"h":"新年","p":"xīnnián","e":"New Year"},
    {"h":"新闻","p":"xīnwén","e":"news"},
    {"h":"新鲜","p":"xīnxiān","e":"fresh"},
    {"h":"信","p":"xìn","e":"to believe; letter"},
    {"h":"信用卡","p":"xìnyòngkǎ","e":"credit card"},
    {"h":"行","p":"xíng","e":"to go; okay"},
    {"h":"行李","p":"xíngli","e":"luggage"},
    {"h":"兴趣","p":"xìngqù","e":"interest"},
    {"h":"休假","p":"xiūjià","e":"to take a holiday"},
    {"h":"需要","p":"xūyào","e":"to need; need"},
    {"h":"选","p":"xuǎn","e":"to choose"},
    {"h":"选择","p":"xuǎnzé","e":"to choose"},
    {"h":"学期","p":"xuéqī","e":"semester"},
    {"h":"牙","p":"yá","e":"tooth"},
    {"h":"牙刷","p":"yáshuā","e":"toothbrush"},
    {"h":"羊","p":"yáng","e":"sheep"},
    {"h":"养","p":"yǎng","e":"to raise, to keep"},
    {"h":"要求","p":"yāoqiú","e":"to demand; requirement"},
    {"h":"页","p":"yè","e":"page"},
    {"h":"一定","p":"yídìng","e":"certain; certainly"},
    {"h":"一共","p":"yígòng","e":"altogether"},
    {"h":"一块儿","p":"yíkuàir","e":"together"},
    {"h":"一样","p":"yíyàng","e":"same"},
    {"h":"以后","p":"yǐhòu","e":"later, after"},
    {"h":"以前","p":"yǐqián","e":"before"},
    {"h":"以上","p":"yǐshàng","e":"above, more than"},
    {"h":"以外","p":"yǐwài","e":"except, besides"},
    {"h":"以为","p":"yǐwéi","e":"to think"},
    {"h":"以下","p":"yǐxià","e":"below, less than"},
    {"h":"一般","p":"yìbān","e":"general, ordinary"},
    {"h":"一边","p":"yìbiān","e":"at the same time"},
    {"h":"一直","p":"yìzhí","e":"always, straight"},
    {"h":"音乐","p":"yīnyuè","e":"music"},
    {"h":"银行","p":"yínháng","e":"bank"},
    {"h":"银行卡","p":"yínhángkǎ","e":"bank card"},
    {"h":"饮料","p":"yǐnliào","e":"beverage"},
    {"h":"应该","p":"yīnggāi","e":"should"},
    {"h":"影响","p":"yǐngxiǎng","e":"to affect; influence"},
    {"h":"用","p":"yòng","e":"to use"},
    {"h":"邮件","p":"yóujiàn","e":"mail"},
    {"h":"游客","p":"yóukè","e":"tourist"},
    {"h":"游戏","p":"yóuxì","e":"game"},
    {"h":"邮箱","p":"yóuxiāng","e":"mailbox"},
    {"h":"有关","p":"yǒuguān","e":"concerning"},
    {"h":"有名","p":"yǒumíng","e":"famous"},
    {"h":"有用","p":"yǒuyòng","e":"useful"},
    {"h":"又","p":"yòu","e":"again, also"},
    {"h":"羽毛球","p":"yǔmáoqiú","e":"badminton"},
    {"h":"语言","p":"yǔyán","e":"language"},
    {"h":"雨衣","p":"yǔyī","e":"raincoat"},
    {"h":"遇到","p":"yùdào","e":"to encounter"},
    {"h":"遇见","p":"yùjiàn","e":"to meet"},
    {"h":"园","p":"yuán","e":"garden"},
    {"h":"员","p":"yuán","e":"suffix for person"},
    {"h":"愿意","p":"yuànyì","e":"willing"},
    {"h":"越","p":"yuè","e":"more, increasingly"},
    {"h":"月亮","p":"yuèliang","e":"moon"},
    {"h":"运动会","p":"yùndònghuì","e":"sports meet"},
    {"h":"运动员","p":"yùndòngyuán","e":"athlete"},
    {"h":"咱们","p":"zánmen","e":"we"},
    {"h":"脏","p":"zāng","e":"dirty"},
    {"h":"怎么办","p":"zěnme bàn","e":"what to do"},
    {"h":"怎样","p":"zěnyàng","e":"how"},
    {"h":"张","p":"zhāng","e":"measure word for flat objects"},
    {"h":"长","p":"zhǎng","e":"to grow"},
    {"h":"着急","p":"zháojí","e":"anxious"},
    {"h":"照","p":"zhào","e":"to shine, to photograph"},
    {"h":"照顾","p":"zhàogù","e":"to take care of"},
    {"h":"照片","p":"zhàopiàn","e":"photo"},
    {"h":"照相","p":"zhàoxiàng","e":"to take a picture"},
    {"h":"直到","p":"zhídào","e":"until"},
    {"h":"只","p":"zhǐ","e":"only, merely"},
    {"h":"纸","p":"zhǐ","e":"paper"},
    {"h":"只能","p":"zhǐ néng","e":"can only"},
    {"h":"只是","p":"zhǐshì","e":"only, merely"},
    {"h":"只要","p":"zhǐyào","e":"as long as"},
    {"h":"只有","p":"zhǐyǒu","e":"only if"},
    {"h":"中","p":"zhōng","e":"middle"},
    {"h":"中间","p":"zhōngjiān","e":"middle, between"},
    {"h":"终于","p":"zhōngyú","e":"finally"},
    {"h":"种","p":"zhǒng","e":"measure word for kinds"},
    {"h":"重要","p":"zhòngyào","e":"important"},
    {"h":"周末","p":"zhōumò","e":"weekend"},
    {"h":"主要","p":"zhǔyào","e":"main"},
    {"h":"注意","p":"zhùyì","e":"to pay attention to"},
    {"h":"住院","p":"zhùyuàn","e":"to be hospitalized"},
    {"h":"字典","p":"zìdiǎn","e":"dictionary"},
    {"h":"自行车","p":"zìxíngchē","e":"bicycle"},
    {"h":"子","p":"zi","e":"noun suffix"},
    {"h":"总","p":"zǒng","e":"always; total"},
    {"h":"总是","p":"zǒngshì","e":"always"},
    {"h":"嘴","p":"zuǐ","e":"mouth"},
    {"h":"最好","p":"zuìhǎo","e":"best"},
    {"h":"最后","p":"zuìhòu","e":"last, final"},
    {"h":"最近","p":"zuìjìn","e":"recently"},
    {"h":"做客","p":"zuòkè","e":"to be a guest"},
    {"h":"作业","p":"zuòyè","e":"homework"}
  ],
  4: [
    {"h":"啊","p":"ā","e":"ah, oh"},
    {"h":"爱情","p":"àiqíng","e":"love"},
    {"h":"爱心","p":"àixīn","e":"compassion, caring"},
    {"h":"安检","p":"ānjiǎn","e":"security check"},
    {"h":"安排","p":"ānpái","e":"to arrange"},
    {"h":"按","p":"àn","e":"to press, according to"},
    {"h":"按时","p":"ànshí","e":"on time, on schedule"},
    {"h":"按照","p":"ànzhào","e":"according to"},
    {"h":"白酒","p":"báijiǔ","e":"liquor, spirit"},
    {"h":"办公","p":"bàngōng","e":"to handle official business"},
    {"h":"办理","p":"bànlǐ","e":"to handle, to process"},
    {"h":"办事","p":"bànshì","e":"to handle matters"},
    {"h":"棒","p":"bàng","e":"great, excellent"},
    {"h":"保护","p":"bǎohù","e":"to protect"},
    {"h":"保证","p":"bǎozhèng","e":"to guarantee"},
    {"h":"抱","p":"bào","e":"to hold, to embrace"},
    {"h":"报考","p":"bàokǎo","e":"to apply for an exam"},
    {"h":"报名","p":"bàomíng","e":"to sign up, to register"},
    {"h":"抱歉","p":"bàoqiàn","e":"sorry, apologetic"},
    {"h":"背","p":"bēi","e":"to carry on the back"},
    {"h":"背包","p":"bēibāo","e":"backpack"},
    {"h":"北部","p":"běibù","e":"northern part, north"},
    {"h":"倍","p":"bèi","e":"times, -fold"},
    {"h":"本科","p":"běnkē","e":"undergraduate program"},
    {"h":"本来","p":"běnlái","e":"originally, actually"},
    {"h":"笨","p":"bèn","e":"stupid, foolish"},
    {"h":"鼻子","p":"bízi","e":"nose"},
    {"h":"笔试","p":"bǐshì","e":"written test"},
    {"h":"毕业","p":"bìyè","e":"to graduate"},
    {"h":"毕业生","p":"bìyèshēng","e":"graduate"},
    {"h":"便于","p":"biànyú","e":"to be convenient for"},
    {"h":"标准","p":"biāozhǔn","e":"standard"},
    {"h":"表","p":"biǎo","e":"watch, meter, table"},
    {"h":"表格","p":"biǎogé","e":"form, table"},
    {"h":"表示","p":"biǎoshì","e":"to express, to indicate"},
    {"h":"表现","p":"biǎoxiàn","e":"to show, to display"},
    {"h":"表扬","p":"biǎoyáng","e":"to praise, to commend"},
    {"h":"饼干","p":"bǐnggān","e":"biscuit, cracker"},
    {"h":"并","p":"bìng","e":"and, also, moreover"},
    {"h":"并且","p":"bìngqiě","e":"and, moreover"},
    {"h":"播放","p":"bōfàng","e":"to broadcast, to play"},
    {"h":"博士","p":"bóshì","e":"doctor"},
    {"h":"不必","p":"búbì","e":"need not, not necessary"},
    {"h":"不便","p":"búbiàn","e":"inconvenient"},
    {"h":"不断","p":"búduàn","e":"continuous, continuously"},
    {"h":"不够","p":"búgòu","e":"not enough, insufficient"},
    {"h":"不过","p":"búguò","e":"but, however"},
    {"h":"不论","p":"búlùn","e":"no matter, regardless"},
    {"h":"步","p":"bù","e":"step, pace"},
    {"h":"部","p":"bù","e":"department, part"},
    {"h":"不得不","p":"bùdébù","e":"have to, cannot but"},
    {"h":"部分","p":"bùfen","e":"part, portion"},
    {"h":"不管","p":"bùguǎn","e":"no matter, regardless"},
    {"h":"不光","p":"bùguāng","e":"not only"},
    {"h":"不仅","p":"bùjǐn","e":"not only"},
    {"h":"不满","p":"bùmǎn","e":"dissatisfied, displeased"},
    {"h":"部门","p":"bùmén","e":"department, unit"},
    {"h":"不如","p":"bùrú","e":"not as good as"},
    {"h":"擦","p":"cā","e":"to wipe, to rub"},
    {"h":"猜","p":"cāi","e":"to guess"},
    {"h":"材料","p":"cáiliào","e":"material, data"},
    {"h":"参观","p":"cānguān","e":"to visit, to tour"},
    {"h":"参赛","p":"cānsài","e":"to enter a competition"},
    {"h":"餐厅","p":"cāntīng","e":"restaurant, dining hall"},
    {"h":"操场","p":"cāochǎng","e":"playground"},
    {"h":"厕所","p":"cèsuǒ","e":"toilet, restroom"},
    {"h":"查看","p":"chákàn","e":"to check, to view"},
    {"h":"茶叶","p":"cháyè","e":"tea leaf"},
    {"h":"查找","p":"cházhǎo","e":"to search for, to look up"},
    {"h":"差点儿","p":"chàdiǎnr","e":"almost, nearly"},
    {"h":"产生","p":"chǎnshēng","e":"to produce, to generate"},
    {"h":"厂","p":"chǎng","e":"factory, plant"},
    {"h":"场","p":"chǎng","e":"measure word for events"},
    {"h":"超过","p":"chāoguò","e":"to exceed, to surpass"},
    {"h":"车速","p":"chēsù","e":"vehicle speed"},
    {"h":"车位","p":"chēwèi","e":"parking space"},
    {"h":"城","p":"chéng","e":"city, town"},
    {"h":"乘","p":"chéng","e":"to ride, to take"},
    {"h":"成功","p":"chénggōng","e":"to succeed"},
    {"h":"乘客","p":"chéngkè","e":"passenger"},
    {"h":"诚实","p":"chéngshí","e":"honest"},
    {"h":"成为","p":"chéngwéi","e":"to become"},
    {"h":"乘坐","p":"chéngzuò","e":"to ride, to take"},
    {"h":"吃惊","p":"chījīng","e":"to be startled, shocked"},
    {"h":"迟","p":"chí","e":"late, delayed"},
    {"h":"重","p":"chóng","e":"again, once more"},
    {"h":"重新","p":"chóngxīn","e":"again, anew"},
    {"h":"出差","p":"chūchāi","e":"to go on business trip"},
    {"h":"出口","p":"chūkǒu","e":"exit"},
    {"h":"出现","p":"chūxiàn","e":"to appear, to emerge"},
    {"h":"出行","p":"chūxíng","e":"to travel, to go out"},
    {"h":"出租","p":"chūzū","e":"to rent out"},
    {"h":"此","p":"cǐ","e":"this"},
    {"h":"此次","p":"cǐcì","e":"this time"},
    {"h":"此外","p":"cǐwài","e":"besides, in addition"},
    {"h":"从此","p":"cóngcǐ","e":"from then on"},
    {"h":"从来","p":"cónglái","e":"always, at all times"},
    {"h":"从中","p":"cóngzhōng","e":"from among"},
    {"h":"粗","p":"cū","e":"coarse, rough, thick"},
    {"h":"粗心","p":"cūxīn","e":"careless"},
    {"h":"村","p":"cūn","e":"village"},
    {"h":"存","p":"cún","e":"to store, to keep"},
    {"h":"错过","p":"cuòguò","e":"to miss, to let slip"},
    {"h":"错误","p":"cuòwù","e":"mistake, error"},
    {"h":"答应","p":"dāying","e":"to agree, to promise"},
    {"h":"答","p":"dá","e":"to answer, to reply"},
    {"h":"答案","p":"dá'àn","e":"answer, solution"},
    {"h":"达到","p":"dádào","e":"to reach, to achieve"},
    {"h":"打招呼","p":"dǎzhāohu","e":"to greet, to say hello"},
    {"h":"打败","p":"dǎbài","e":"to defeat, to beat"},
    {"h":"打工","p":"dǎgōng","e":"to work a temporary job"},
    {"h":"打扰","p":"dǎrǎo","e":"to disturb, to bother"},
    {"h":"打印","p":"dǎyìn","e":"to print"},
    {"h":"打印机","p":"dǎyìnjī","e":"printer"},
    {"h":"打折","p":"dǎzhé","e":"to give a discount"},
    {"h":"打针","p":"dǎzhēn","e":"to get an injection"},
    {"h":"大巴","p":"dàbā","e":"large bus, coach"},
    {"h":"大大","p":"dàdà","e":"greatly, significantly"},
    {"h":"大夫","p":"dàifu","e":"doctor"},
    {"h":"大量","p":"dàliàng","e":"large quantity"},
    {"h":"大赛","p":"dàsài","e":"major competition"},
    {"h":"大厅","p":"dàtīng","e":"hall, lobby"},
    {"h":"大约","p":"dàyuē","e":"approximately, about"},
    {"h":"大自然","p":"dàzìrán","e":"nature, the natural world"},
    {"h":"待","p":"dāi","e":"to stay"},
    {"h":"戴","p":"dài","e":"to wear, to put on"},
    {"h":"袋子","p":"dàizi","e":"bag, sack"},
    {"h":"单位","p":"dānwèi","e":"unit, department"},
    {"h":"当","p":"dāng","e":"to serve as, to be"},
    {"h":"当时","p":"dāngshí","e":"at that time, then"},
    {"h":"刀","p":"dāo","e":"knife"},
    {"h":"导游","p":"dǎoyóu","e":"tour guide"},
    {"h":"倒","p":"dào","e":"to fall, to collapse"},
    {"h":"道","p":"dào","e":"path, way, method"},
    {"h":"到底","p":"dàodǐ","e":"finally, after all"},
    {"h":"到来","p":"dàolái","e":"to arrive"},
    {"h":"道路","p":"dàolù","e":"road, path"},
    {"h":"道歉","p":"dàoqiàn","e":"to apologize"},
    {"h":"得意","p":"déyì","e":"proud, complacent"},
    {"h":"登机","p":"dēngjī","e":"to board a plane"},
    {"h":"等","p":"děng","e":"and so on, etc."},
    {"h":"等到","p":"děngdào","e":"until, by the time"},
    {"h":"低","p":"dī","e":"low"},
    {"h":"低价","p":"dījià","e":"low price"},
    {"h":"低温","p":"dīwēn","e":"low temperature"},
    {"h":"低于","p":"dīyú","e":"to be lower than"},
    {"h":"底","p":"dǐ","e":"bottom, base"},
    {"h":"底下","p":"dǐxia","e":"below, underneath"},
    {"h":"地球","p":"dìqiú","e":"earth"},
    {"h":"地址","p":"dìzhǐ","e":"address"},
    {"h":"点名","p":"diǎnmíng","e":"to call the roll"},
    {"h":"点头","p":"diǎntóu","e":"to nod"},
    {"h":"电动车","p":"diàndòngchē","e":"electric vehicle"},
    {"h":"电视剧","p":"diànshìjù","e":"TV drama"},
    {"h":"掉","p":"diào","e":"to fall, to drop"},
    {"h":"调查","p":"diàochá","e":"to investigate"},
    {"h":"订","p":"dìng","e":"to order, to book"},
    {"h":"定","p":"dìng","e":"to fix, to set"},
    {"h":"东部","p":"dōngbù","e":"eastern part"},
    {"h":"动车","p":"dòngchē","e":"high-speed train"},
    {"h":"动作","p":"dòngzuò","e":"movement, action"},
    {"h":"读者","p":"dúzhě","e":"reader"},
    {"h":"堵车","p":"dǔchē","e":"traffic jam"},
    {"h":"度假","p":"dùjià","e":"to go on vacation"},
    {"h":"肚子","p":"dùzi","e":"belly, stomach"},
    {"h":"短信","p":"duǎnxìn","e":"text message"},
    {"h":"队","p":"duì","e":"team, squad"},
    {"h":"对方","p":"duìfāng","e":"the other party"},
    {"h":"对面","p":"duìmiàn","e":"opposite side"},
    {"h":"对于","p":"duìyú","e":"regarding, concerning"},
    {"h":"队员","p":"duìyuán","e":"team member"},
    {"h":"队长","p":"duìzhǎng","e":"team leader"},
    {"h":"顿","p":"dùn","e":"measure word for meals"},
    {"h":"多么","p":"duōme","e":"how, so, what"},
    {"h":"多数","p":"duōshù","e":"majority"},
    {"h":"多样","p":"duōyàng","e":"diverse, varied"},
    {"h":"而","p":"ér","e":"but, and, yet"},
    {"h":"儿童","p":"értóng","e":"child"},
    {"h":"发出","p":"fāchū","e":"to send out, to issue"},
    {"h":"发送","p":"fāsòng","e":"to send"},
    {"h":"法","p":"fǎ","e":"law"},
    {"h":"法律","p":"fǎlǜ","e":"law"},
    {"h":"翻译","p":"fānyì","e":"to translate"},
    {"h":"烦","p":"fán","e":"annoyed, vexed"},
    {"h":"烦恼","p":"fánnǎo","e":"worried, distressed"},
    {"h":"反对","p":"fǎnduì","e":"to oppose"},
    {"h":"方面","p":"fāngmiàn","e":"aspect, side"},
    {"h":"方式","p":"fāngshì","e":"way, method"},
    {"h":"房东","p":"fángdōng","e":"landlord"},
    {"h":"房租","p":"fángzū","e":"rent"},
    {"h":"分数","p":"fēnshù","e":"score, grade"},
    {"h":"分为","p":"fēnwéi","e":"to be divided into"},
    {"h":"份","p":"fèn","e":"measure word for copies"},
    {"h":"丰富","p":"fēngfù","e":"rich, abundant"},
    {"h":"风景","p":"fēngjǐng","e":"scenery, landscape"},
    {"h":"否则","p":"fǒuzé","e":"otherwise, if not"},
    {"h":"幅","p":"fú","e":"measure word for paintings"},
    {"h":"符合","p":"fúhé","e":"to conform to"},
    {"h":"付","p":"fù","e":"to pay"},
    {"h":"父母","p":"fùmǔ","e":"parents"},
    {"h":"父女","p":"fùnǚ","e":"father and daughter"},
    {"h":"父亲","p":"fùqīn","e":"father"},
    {"h":"复印","p":"fùyìn","e":"to photocopy"},
    {"h":"复杂","p":"fùzá","e":"complicated, complex"},
    {"h":"负责","p":"fùzé","e":"to be responsible"},
    {"h":"负责人","p":"fùzérén","e":"person in charge"},
    {"h":"父子","p":"fùzǐ","e":"father and son"},
    {"h":"改","p":"gǎi","e":"to change, to alter"},
    {"h":"改变","p":"gǎibiàn","e":"to change"},
    {"h":"干","p":"gān","e":"dry"},
    {"h":"干杯","p":"gānbēi","e":"to toast, cheers"},
    {"h":"赶","p":"gǎn","e":"to hurry, to catch up"},
    {"h":"敢","p":"gǎn","e":"to dare"},
    {"h":"感","p":"gǎn","e":"sense, feeling"},
    {"h":"感动","p":"gǎndòng","e":"moved, touched"},
    {"h":"赶紧","p":"gǎnjǐn","e":"quickly, promptly"},
    {"h":"感觉","p":"gǎnjué","e":"feeling, to feel"},
    {"h":"赶快","p":"gǎnkuài","e":"quickly, at once"},
    {"h":"感情","p":"gǎnqíng","e":"emotion, feeling"},
    {"h":"感人","p":"gǎnrén","e":"touching, moving"},
    {"h":"赶上","p":"gǎnshàng","e":"to catch up"},
    {"h":"感受","p":"gǎnshòu","e":"feeling, to feel"},
    {"h":"感谢","p":"gǎnxiè","e":"to thank"},
    {"h":"干活儿","p":"gànhuór","e":"to work"},
    {"h":"钢琴","p":"gāngqín","e":"piano"},
    {"h":"高价","p":"gāojià","e":"high price"},
    {"h":"高考","p":"gāokǎo","e":"college entrance exam"},
    {"h":"高速","p":"gāosù","e":"high speed"},
    {"h":"高温","p":"gāowēn","e":"high temperature"},
    {"h":"高于","p":"gāoyú","e":"higher than"},
    {"h":"胳膊","p":"gēbo","e":"arm"},
    {"h":"歌声","p":"gēshēng","e":"sound of singing"},
    {"h":"歌手","p":"gēshǒu","e":"singer"},
    {"h":"各","p":"gè","e":"each, every"},
    {"h":"各地","p":"gèdì","e":"various places"},
    {"h":"各个","p":"gègè","e":"each, every"},
    {"h":"各位","p":"gèwèi","e":"everyone, all"},
    {"h":"各种","p":"gèzhǒng","e":"various kinds"},
    {"h":"更加","p":"gèngjiā","e":"more, even more"},
    {"h":"工厂","p":"gōngchǎng","e":"factory"},
    {"h":"功夫","p":"gōngfu","e":"kung fu, skill"},
    {"h":"公共","p":"gōnggòng","e":"public, common"},
    {"h":"功课","p":"gōngkè","e":"schoolwork"},
    {"h":"公里","p":"gōnglǐ","e":"kilometer"},
    {"h":"公路","p":"gōnglù","e":"highway, road"},
    {"h":"工人","p":"gōngrén","e":"worker"},
    {"h":"工资","p":"gōngzī","e":"wage, salary"},
    {"h":"共","p":"gòng","e":"together, in total"},
    {"h":"共同","p":"gòngtóng","e":"common, joint"},
    {"h":"够","p":"gòu","e":"enough"},
    {"h":"购买","p":"gòumǎi","e":"to purchase"},
    {"h":"购物","p":"gòuwù","e":"to shop"},
    {"h":"估计","p":"gūjì","e":"to estimate, to guess"},
    {"h":"姑娘","p":"gūniang","e":"girl"},
    {"h":"鼓励","p":"gǔlì","e":"to encourage"},
    {"h":"顾客","p":"gùkè","e":"customer"},
    {"h":"故意","p":"gùyì","e":"deliberately"},
    {"h":"挂","p":"guà","e":"to hang"},
    {"h":"关键","p":"guānjiàn","e":"key, crucial"},
    {"h":"观看","p":"guānkàn","e":"to watch, to view"},
    {"h":"观众","p":"guānzhòng","e":"audience"},
    {"h":"管","p":"guǎn","e":"to manage, to care about"},
    {"h":"管理","p":"guǎnlǐ","e":"to manage"},
    {"h":"光","p":"guāng","e":"light, only"},
    {"h":"广播","p":"guǎngbō","e":"broadcast"},
    {"h":"广告","p":"guǎnggào","e":"advertisement"},
    {"h":"逛","p":"guàng","e":"to stroll, to browse"},
    {"h":"规定","p":"guīdìng","e":"to stipulate, rule"},
    {"h":"国籍","p":"guójí","e":"nationality"},
    {"h":"国际","p":"guójì","e":"international"},
    {"h":"果汁","p":"guǒzhī","e":"fruit juice"},
    {"h":"过程","p":"guòchéng","e":"process"},
    {"h":"海洋","p":"hǎiyáng","e":"ocean, sea"},
    {"h":"害羞","p":"hàixiū","e":"shy, bashful"},
    {"h":"寒假","p":"hánjià","e":"winter vacation"},
    {"h":"寒冷","p":"hánlěng","e":"cold, frigid"},
    {"h":"喊","p":"hǎn","e":"to shout"},
    {"h":"汗","p":"hàn","e":"sweat"},
    {"h":"航班","p":"hángbān","e":"flight"},
    {"h":"好处","p":"hǎochù","e":"benefit"},
    {"h":"好好","p":"hǎohǎo","e":"well, thoroughly"},
    {"h":"好笑","p":"hǎoxiào","e":"funny, ridiculous"},
    {"h":"合格","p":"hégé","e":"qualified"},
    {"h":"盒子","p":"hézi","e":"box"},
    {"h":"红包","p":"hóngbāo","e":"red envelope"},
    {"h":"厚","p":"hòu","e":"thick"},
    {"h":"后悔","p":"hòuhuǐ","e":"to regret"},
    {"h":"忽然","p":"hūrán","e":"suddenly"},
    {"h":"互联网","p":"hùliánwǎng","e":"Internet"},
    {"h":"护士","p":"hùshi","e":"nurse"},
    {"h":"互相","p":"hùxiāng","e":"each other"},
    {"h":"话剧","p":"huàjù","e":"drama"},
    {"h":"怀疑","p":"huáiyí","e":"to doubt"},
    {"h":"坏处","p":"huàichù","e":"disadvantage, harm"},
    {"h":"环保","p":"huánbǎo","e":"environmental protection"},
    {"h":"换乘","p":"huànchéng","e":"to transfer"},
    {"h":"回复","p":"huífù","e":"to reply"},
    {"h":"回信","p":"huíxìn","e":"to write back"},
    {"h":"回忆","p":"huíyì","e":"memory"},
    {"h":"会员","p":"huìyuán","e":"membership"},
    {"h":"活","p":"huó","e":"to live, alive"},
    {"h":"活动","p":"huódòng","e":"activity, event"},
    {"h":"活泼","p":"huópō","e":"lively"},
    {"h":"火","p":"huǒ","e":"fire, popular"},
    {"h":"货","p":"huò","e":"goods, commodity"},
    {"h":"获得","p":"huòdé","e":"to get, to obtain"},
    {"h":"获奖","p":"huòjiǎng","e":"to win a prize"},
    {"h":"获取","p":"huòqǔ","e":"to gain, to obtain"},
    {"h":"基本","p":"jīběn","e":"basic, fundamental"},
    {"h":"基本上","p":"jīběnshàng","e":"basically"},
    {"h":"基础","p":"jīchǔ","e":"basics, foundation"},
    {"h":"激动","p":"jīdòng","e":"excited, agitated"},
    {"h":"积极","p":"jījí","e":"positive, active"},
    {"h":"积累","p":"jīlěi","e":"to accumulate"},
    {"h":"及时","p":"jíshí","e":"timely, prompt"},
    {"h":"即使","p":"jíshǐ","e":"even if"},
    {"h":"既","p":"jì","e":"already, since"},
    {"h":"寄","p":"jì","e":"to send"},
    {"h":"计划","p":"jìhuà","e":"plan, to plan"},
    {"h":"既然","p":"jìrán","e":"since"},
    {"h":"技术","p":"jìshù","e":"technology"},
    {"h":"继续","p":"jìxù","e":"to continue"},
    {"h":"记者","p":"jìzhě","e":"reporter"},
    {"h":"加班","p":"jiābān","e":"to work overtime"},
    {"h":"家具","p":"jiājù","e":"furniture"},
    {"h":"加快","p":"jiākuài","e":"to speed up"},
    {"h":"加强","p":"jiāqiáng","e":"to strengthen"},
    {"h":"加入","p":"jiārù","e":"to join"},
    {"h":"加上","p":"jiāshàng","e":"plus, add"},
    {"h":"家庭","p":"jiātíng","e":"family"},
    {"h":"家乡","p":"jiāxiāng","e":"hometown"},
    {"h":"加油","p":"jiāyóu","e":"to refuel, go for it"},
    {"h":"加油站","p":"jiāyóuzhàn","e":"gas station"},
    {"h":"家长","p":"jiāzhǎng","e":"parent"},
    {"h":"假","p":"jiǎ","e":"false, fake"},
    {"h":"价格","p":"jiàgé","e":"price"},
    {"h":"价钱","p":"jiàqián","e":"price"},
    {"h":"假日","p":"jiàrì","e":"holiday, vacation"},
    {"h":"减","p":"jiǎn","e":"to reduce, to subtract"},
    {"h":"减轻","p":"jiǎnqīng","e":"to lighten, to ease"},
    {"h":"减少","p":"jiǎnshǎo","e":"to reduce, to decrease"},
    {"h":"健身","p":"jiànshēn","e":"to exercise, fitness"},
    {"h":"健身房","p":"jiànshēnfáng","e":"gym"},
    {"h":"建议","p":"jiànyì","e":"to suggest, suggestion"},
    {"h":"江","p":"jiāng","e":"river"},
    {"h":"将","p":"jiāng","e":"will, shall"},
    {"h":"将来","p":"jiānglái","e":"future"},
    {"h":"将要","p":"jiāngyào","e":"will, be about to"},
    {"h":"奖","p":"jiǎng","e":"prize, award"},
    {"h":"奖金","p":"jiǎngjīn","e":"bonus, prize money"},
    {"h":"奖学金","p":"jiǎngxuéjīn","e":"scholarship"},
    {"h":"降","p":"jiàng","e":"to fall, to drop"},
    {"h":"降低","p":"jiàngdī","e":"to reduce, to lower"},
    {"h":"降价","p":"jiàngjià","e":"to reduce price"},
    {"h":"降落","p":"jiàngluò","e":"to descend, to land"},
    {"h":"降温","p":"jiàngwēn","e":"to cool down"},
    {"h":"交","p":"jiāo","e":"to hand in, to submit"},
    {"h":"骄傲","p":"jiāo'ào","e":"proud, arrogant"},
    {"h":"交警","p":"jiāojǐng","e":"traffic police"},
    {"h":"交流","p":"jiāoliú","e":"to communicate"},
    {"h":"郊区","p":"jiāoqū","e":"suburb"},
    {"h":"交通","p":"jiāotōng","e":"traffic"},
    {"h":"教练","p":"jiàoliàn","e":"coach"},
    {"h":"教师","p":"jiàoshī","e":"teacher"},
    {"h":"教授","p":"jiàoshòu","e":"professor"},
    {"h":"教学","p":"jiàoxué","e":"to teach"},
    {"h":"教育","p":"jiàoyù","e":"education"},
    {"h":"叫作","p":"jiàozuò","e":"to be called"},
    {"h":"街道","p":"jiēdào","e":"street"},
    {"h":"接受","p":"jiēshòu","e":"to accept"},
    {"h":"接着","p":"jiēzhe","e":"to continue, then"},
    {"h":"警察","p":"jǐngchá","e":"police"},
    {"h":"景点","p":"jǐngdiǎn","e":"scenic spot"},
    {"h":"景区","p":"jǐngqū","e":"scenic area"},
    {"h":"景色","p":"jǐngsè","e":"scenery"},
    {"h":"竟然","p":"jìngrán","e":"unexpectedly"},
    {"h":"竞争","p":"jìngzhēng","e":"to compete"},
    {"h":"镜子","p":"jìngzi","e":"mirror"},
    {"h":"究竟","p":"jiūjìng","e":"actually, exactly"},
    {"h":"就是","p":"jiùshì","e":"precisely, exactly"},
    {"h":"举","p":"jǔ","e":"to raise, to lift"},
    {"h":"举办","p":"jǔbàn","e":"to hold, to host"},
    {"h":"举例","p":"jǔlì","e":"to give an example"},
    {"h":"举行","p":"jǔxíng","e":"to hold, to conduct"},
    {"h":"聚","p":"jù","e":"to gather"},
    {"h":"聚餐","p":"jùcān","e":"to dine together"},
    {"h":"聚会","p":"jùhuì","e":"to get together, party"},
    {"h":"拒绝","p":"jùjué","e":"to refuse, to reject"},
    {"h":"距离","p":"jùlí","e":"distance, gap"},
    {"h":"剧院","p":"jùyuàn","e":"theater"},
    {"h":"开玩笑","p":"kāiwánxiào","e":"to make fun of"},
    {"h":"看法","p":"kànfǎ","e":"view, opinion"},
    {"h":"烤","p":"kǎo","e":"to bake, to roast"},
    {"h":"考虑","p":"kǎolǜ","e":"to consider"},
    {"h":"考生","p":"kǎoshēng","e":"examinee"},
    {"h":"棵","p":"kē","e":"measure word for trees"},
    {"h":"科技","p":"kējì","e":"science and technology"},
    {"h":"科学","p":"kēxué","e":"science"},
    {"h":"咳","p":"ké","e":"to cough"},
    {"h":"咳嗽","p":"késou","e":"to cough"},
    {"h":"可惜","p":"kěxī","e":"regrettable"},
    {"h":"克","p":"kè","e":"gram"},
    {"h":"课程","p":"kèchéng","e":"curriculum"},
    {"h":"客气","p":"kèqi","e":"polite, courteous"},
    {"h":"课堂","p":"kètáng","e":"classroom"},
    {"h":"客厅","p":"kètīng","e":"living room"},
    {"h":"肯定","p":"kěndìng","e":"to be certain"},
    {"h":"空","p":"kōng","e":"empty, vacant"},
    {"h":"空气","p":"kōngqì","e":"air"},
    {"h":"恐怕","p":"kǒngpà","e":"to fear, perhaps"},
    {"h":"口语","p":"kǒuyǔ","e":"spoken language"},
    {"h":"苦","p":"kǔ","e":"bitter"},
    {"h":"快餐","p":"kuàicān","e":"fast food"},
    {"h":"快递","p":"kuàidì","e":"express delivery"},
    {"h":"快速","p":"kuàisù","e":"fast, high-speed"},
    {"h":"困","p":"kùn","e":"sleepy, tired"},
    {"h":"困难","p":"kùnnan","e":"difficult, difficulty"},
    {"h":"拉","p":"lā","e":"to pull, to drag"},
    {"h":"垃圾","p":"lājī","e":"garbage, trash"},
    {"h":"辣","p":"là","e":"hot, spicy"},
    {"h":"来不及","p":"láibují","e":"not enough time"},
    {"h":"来得及","p":"láidejí","e":"still have time"},
    {"h":"懒","p":"lǎn","e":"lazy, idle"},
    {"h":"浪费","p":"làngfèi","e":"to waste"},
    {"h":"浪漫","p":"làngmàn","e":"romantic"},
    {"h":"老虎","p":"lǎohǔ","e":"tiger"},
    {"h":"老家","p":"lǎojiā","e":"hometown"},
    {"h":"老年","p":"lǎonián","e":"elderly"},
    {"h":"老是","p":"lǎoshì","e":"always, constantly"},
    {"h":"冷静","p":"lěngjìng","e":"calm, cool-headed"},
    {"h":"理发","p":"lǐfà","e":"to have a haircut"},
    {"h":"理解","p":"lǐjiě","e":"to understand"},
    {"h":"礼貌","p":"lǐmào","e":"courtesy, politeness"},
    {"h":"理想","p":"lǐxiǎng","e":"ideal, dream"},
    {"h":"厉害","p":"lìhai","e":"severe, impressive"},
    {"h":"力气","p":"lìqi","e":"strength, power"},
    {"h":"例如","p":"lìrú","e":"for example"},
    {"h":"例子","p":"lìzi","e":"example, instance"},
    {"h":"俩","p":"liǎ","e":"two, both"},
    {"h":"连","p":"lián","e":"even, to link"},
    {"h":"联系","p":"liánxì","e":"to contact"},
    {"h":"凉","p":"liáng","e":"cool, cold"},
    {"h":"量","p":"liáng","e":"to measure"},
    {"h":"亮","p":"liàng","e":"bright, light"},
    {"h":"列","p":"liè","e":"to list, row"},
    {"h":"零下","p":"língxià","e":"below zero"},
    {"h":"零花钱","p":"línghuāqián","e":"pocket money"},
    {"h":"零钱","p":"língqián","e":"change"},
    {"h":"零食","p":"língshí","e":"snacks"},
    {"h":"另","p":"lìng","e":"other, another"},
    {"h":"另外","p":"lìngwài","e":"other, in addition"},
    {"h":"留","p":"liú","e":"to stay, to keep"},
    {"h":"流","p":"liú","e":"to flow"},
    {"h":"流利","p":"liúlì","e":"fluent, smooth"},
    {"h":"留下","p":"liúxia","e":"to leave behind"},
    {"h":"流行","p":"liúxíng","e":"to be popular"},
    {"h":"路过","p":"lùguò","e":"to pass by"},
    {"h":"旅馆","p":"lǚguǎn","e":"hotel, inn"},
    {"h":"旅客","p":"lǚkè","e":"traveler, passenger"},
    {"h":"旅行","p":"lǚxíng","e":"to travel"},
    {"h":"律师","p":"lǜshī","e":"lawyer"},
    {"h":"乱","p":"luàn","e":"messy, disorderly"},
    {"h":"落","p":"luò","e":"to fall, to drop"},
    {"h":"麻烦","p":"máfan","e":"troublesome, trouble"},
    {"h":"馒头","p":"mántou","e":"steamed bun"},
    {"h":"满","p":"mǎn","e":"full, filled"},
    {"h":"毛巾","p":"máojīn","e":"towel"},
    {"h":"毛衣","p":"máoyī","e":"sweater"},
    {"h":"帽子","p":"màozi","e":"hat, cap"},
    {"h":"美","p":"měi","e":"beautiful, pretty"},
    {"h":"美好","p":"měihǎo","e":"beautiful, splendid"},
    {"h":"美景","p":"měijǐng","e":"beautiful scenery"},
    {"h":"美丽","p":"měilì","e":"beautiful, lovely"},
    {"h":"美食","p":"měishí","e":"delicious food"},
    {"h":"梦","p":"mèng","e":"dream"},
    {"h":"梦想","p":"mèngxiǎng","e":"to dream, dream"},
    {"h":"密码","p":"mìmǎ","e":"password, PIN code"},
    {"h":"免费","p":"miǎnfèi","e":"free of charge"},
    {"h":"面对","p":"miànduì","e":"to face, to confront"},
    {"h":"面试","p":"miànshì","e":"interview"},
    {"h":"秒","p":"miǎo","e":"second"},
    {"h":"民族","p":"mínzú","e":"ethnic group"},
    {"h":"末","p":"mò","e":"end, last"},
    {"h":"母女","p":"mǔnǚ","e":"mother and daughter"},
    {"h":"母亲","p":"mǔqīn","e":"mother"},
    {"h":"母子","p":"mǔzǐ","e":"mother and son"},
    {"h":"目标","p":"mùbiāo","e":"goal, target"},
    {"h":"目的","p":"mùdì","e":"purpose, aim"},
    {"h":"目的地","p":"mùdìdì","e":"destination"},
    {"h":"目前","p":"mùqián","e":"currently, at present"},
    {"h":"耐心","p":"nàixīn","e":"patient, patience"},
    {"h":"南部","p":"nánbù","e":"southern part"},
    {"h":"难道","p":"nándào","e":"could it be that"},
    {"h":"男士","p":"nánshì","e":"man, gentleman"},
    {"h":"难受","p":"nánshòu","e":"uncomfortable"},
    {"h":"难忘","p":"nánwàng","e":"unforgettable"},
    {"h":"男性","p":"nánxìng","e":"male"},
    {"h":"内","p":"nèi","e":"inside, within"},
    {"h":"内容","p":"nèiróng","e":"content, substance"},
    {"h":"内心","p":"nèixīn","e":"heart, inner self"},
    {"h":"能否","p":"néngfǒu","e":"whether or not"},
    {"h":"能够","p":"nénggòu","e":"can, be able to"},
    {"h":"能力","p":"nénglì","e":"ability, capability"},
    {"h":"嗯","p":"ǹg","e":"uh-huh, hmm"},
    {"h":"年底","p":"niándǐ","e":"end of the year"},
    {"h":"年龄","p":"niánlíng","e":"age"},
    {"h":"农村","p":"nóngcūn","e":"rural area"},
    {"h":"弄","p":"nòng","e":"to do, to handle"},
    {"h":"女性","p":"nǚxìng","e":"female"},
    {"h":"暖和","p":"nuǎnhuo","e":"warm"},
    {"h":"偶尔","p":"ǒu'ěr","e":"occasionally"},
    {"h":"拍","p":"pāi","e":"to pat, to take photo"},
    {"h":"排","p":"pái","e":"to line up, row"},
    {"h":"牌","p":"pái","e":"card, brand, sign"},
    {"h":"排队","p":"páiduì","e":"to line up, to queue"},
    {"h":"排球","p":"páiqiú","e":"volleyball"},
    {"h":"牌子","p":"páizi","e":"brand, sign, label"},
    {"h":"判断","p":"pànduàn","e":"to judge"},
    {"h":"陪","p":"péi","e":"to accompany"},
    {"h":"批评","p":"pīpíng","e":"to criticize"},
    {"h":"皮肤","p":"pífū","e":"skin"},
    {"h":"脾气","p":"píqi","e":"temperament, temper"},
    {"h":"皮鞋","p":"píxié","e":"leather shoes"},
    {"h":"篇","p":"piān","e":"measure word for articles"},
    {"h":"片","p":"piàn","e":"piece, slice"},
    {"h":"乒乓球","p":"pīngpāngqiú","e":"table tennis"},
    {"h":"平常","p":"píngcháng","e":"ordinary, usually"},
    {"h":"破","p":"pò","e":"broken, to break"},
    {"h":"葡萄","p":"pútao","e":"grape"},
    {"h":"葡萄酒","p":"pútaojiǔ","e":"wine"},
    {"h":"普遍","p":"pǔbiàn","e":"widespread, common"},
    {"h":"普通","p":"pǔtōng","e":"ordinary, common"},
    {"h":"普通话","p":"pǔtōnghuà","e":"Mandarin Chinese"},
    {"h":"期","p":"qī","e":"period, phase"},
    {"h":"期末","p":"qīmò","e":"end of term"},
    {"h":"期中","p":"qīzhōng","e":"midterm"},
    {"h":"其次","p":"qícì","e":"next, secondly"},
    {"h":"其中","p":"qízhōng","e":"among them"},
    {"h":"起到","p":"qǐdào","e":"to play the role of"},
    {"h":"气","p":"qì","e":"air, gas, breath"},
    {"h":"气候","p":"qìhòu","e":"climate"},
    {"h":"汽水","p":"qìshuǐ","e":"soda, soft drink"},
    {"h":"气温","p":"qìwēn","e":"air temperature"},
    {"h":"千克","p":"qiānkè","e":"kilogram"},
    {"h":"千万","p":"qiānwàn","e":"ten million, by all means"},
    {"h":"签证","p":"qiānzhèng","e":"visa"},
    {"h":"前方","p":"qiánfāng","e":"ahead, front"},
    {"h":"前后","p":"qiánhòu","e":"front and back, around"},
    {"h":"强","p":"qiáng","e":"strong, powerful"},
    {"h":"敲","p":"qiāo","e":"to knock, to tap"},
    {"h":"桥","p":"qiáo","e":"bridge"},
    {"h":"巧","p":"qiǎo","e":"skillful, clever"},
    {"h":"巧克力","p":"qiǎokèlì","e":"chocolate"},
    {"h":"亲戚","p":"qīnqi","e":"relative"},
    {"h":"琴","p":"qín","e":"musical instrument"},
    {"h":"轻","p":"qīng","e":"light, gentle"},
    {"h":"青年","p":"qīngnián","e":"youth, young people"},
    {"h":"轻松","p":"qīngsōng","e":"relaxed, easy"},
    {"h":"情况","p":"qíngkuàng","e":"situation"},
    {"h":"庆祝","p":"qìngzhù","e":"to celebrate"},
    {"h":"球队","p":"qiúduì","e":"sports team"},
    {"h":"球迷","p":"qiúmí","e":"fan, enthusiast"},
    {"h":"全","p":"quán","e":"whole, entire"},
    {"h":"全部","p":"quánbù","e":"all, the whole"},
    {"h":"全都","p":"quándōu","e":"all, entirely"},
    {"h":"全球","p":"quánqiú","e":"the whole world"},
    {"h":"全身","p":"quánshēn","e":"whole body"},
    {"h":"缺","p":"quē","e":"to lack"},
    {"h":"缺点","p":"quēdiǎn","e":"shortcoming, defect"},
    {"h":"缺少","p":"quēshǎo","e":"to lack"},
    {"h":"却","p":"què","e":"but, yet, however"},
    {"h":"确实","p":"quèshí","e":"indeed, really"},
    {"h":"然而","p":"rán'ér","e":"however, but"},
    {"h":"热闹","p":"rènao","e":"lively, bustling"},
    {"h":"人生","p":"rénshēng","e":"life"},
    {"h":"人数","p":"rénshù","e":"number of people"},
    {"h":"人员","p":"rényuán","e":"personnel, staff"},
    {"h":"任何","p":"rènhé","e":"any, whatever"},
    {"h":"任务","p":"rènwu","e":"task, mission"},
    {"h":"扔","p":"rēng","e":"to throw, to toss"},
    {"h":"仍","p":"réng","e":"still, yet"},
    {"h":"仍然","p":"réngrán","e":"still, yet"},
    {"h":"日常","p":"rìcháng","e":"daily, everyday"},
    {"h":"日记","p":"rìjì","e":"diary"},
    {"h":"日期","p":"rìqī","e":"date"},
    {"h":"日子","p":"rìzi","e":"day, life, time"},
    {"h":"入","p":"rù","e":"to enter, to go in"},
    {"h":"入口","p":"rùkǒu","e":"entrance"},
    {"h":"入学","p":"rùxué","e":"to enter school"},
    {"h":"入住","p":"rùzhù","e":"to check in"},
    {"h":"散步","p":"sànbù","e":"to take a walk"},
    {"h":"扫码","p":"sǎomǎ","e":"to scan a code"},
    {"h":"森林","p":"sēnlín","e":"forest"},
    {"h":"商量","p":"shāngliang","e":"to discuss"},
    {"h":"商品","p":"shāngpǐn","e":"product, commodity"},
    {"h":"伤心","p":"shāngxīn","e":"sad, heartbroken"},
    {"h":"上门","p":"shàngmén","e":"to visit"},
    {"h":"稍","p":"shāo","e":"a little, slightly"},
    {"h":"稍微","p":"shāowēi","e":"a little, slightly"},
    {"h":"少见","p":"shǎojiàn","e":"rare, seldom seen"},
    {"h":"少量","p":"shǎoliàng","e":"small amount"},
    {"h":"少数","p":"shǎoshù","e":"minority"},
    {"h":"少年","p":"shàonián","e":"teenager, youth"},
    {"h":"社会","p":"shèhuì","e":"society"},
    {"h":"摄氏度","p":"shèshìdù","e":"degrees Celsius"},
    {"h":"身","p":"shēn","e":"body, oneself"},
    {"h":"深","p":"shēn","e":"deep, profound"},
    {"h":"身份证","p":"shēnfènzhèng","e":"ID card"},
    {"h":"申请","p":"shēnqǐng","e":"to apply"},
    {"h":"甚至","p":"shènzhì","e":"even, so much as"},
    {"h":"生","p":"shēng","e":"to give birth, to grow"},
    {"h":"生命","p":"shēngmìng","e":"life"},
    {"h":"生意","p":"shēngyi","e":"business, trade"},
    {"h":"省","p":"shěng","e":"province"},
    {"h":"剩","p":"shèng","e":"to be left over"},
    {"h":"失败","p":"shībài","e":"to fail"},
    {"h":"师傅","p":"shīfu","e":"master, skilled worker"},
    {"h":"失去","p":"shīqù","e":"to lose"},
    {"h":"师生","p":"shīshēng","e":"teacher and student"},
    {"h":"失望","p":"shīwàng","e":"to be disappointed"},
    {"h":"十分","p":"shífēn","e":"very, extremely"},
    {"h":"实际","p":"shíjì","e":"reality, actuality"},
    {"h":"时间表","p":"shíjiānbiǎo","e":"schedule, timetable"},
    {"h":"实际上","p":"shíjìshàng","e":"actually, in fact"},
    {"h":"食品","p":"shípǐn","e":"food, provisions"},
    {"h":"食堂","p":"shítáng","e":"cafeteria"},
    {"h":"食物","p":"shíwù","e":"food"},
    {"h":"实在","p":"shízài","e":"honest, reliable"},
    {"h":"十字路口","p":"shízìlùkǒu","e":"intersection"},
    {"h":"使","p":"shǐ","e":"to make, to cause"},
    {"h":"使馆","p":"shǐguǎn","e":"embassy"},
    {"h":"使用","p":"shǐyòng","e":"to use"},
    {"h":"市场","p":"shìchǎng","e":"market"},
    {"h":"是否","p":"shìfǒu","e":"whether or not"},
    {"h":"适合","p":"shìhé","e":"to suit, to fit"},
    {"h":"世纪","p":"shìjì","e":"century"},
    {"h":"视频","p":"shìpín","e":"video"},
    {"h":"市区","p":"shìqū","e":"urban area"},
    {"h":"试题","p":"shìtí","e":"test questions"},
    {"h":"适应","p":"shìyìng","e":"to adapt"},
    {"h":"收费","p":"shōufèi","e":"to charge a fee"},
    {"h":"收入","p":"shōurù","e":"income"},
    {"h":"收拾","p":"shōushi","e":"to tidy up"},
    {"h":"收听","p":"shōutīng","e":"to listen in"},
    {"h":"首","p":"shǒu","e":"measure word for songs"},
    {"h":"首都","p":"shǒudū","e":"capital"},
    {"h":"首先","p":"shǒuxiān","e":"first, firstly"},
    {"h":"说法","p":"shuōfǎ","e":"way of saying"},
    {"h":"说明","p":"shuōmíng","e":"to explain"},
    {"h":"说明书","p":"shuōmíngshū","e":"instruction manual"},
    {"h":"硕士","p":"shuòshì","e":"master"},
    {"h":"死","p":"sǐ","e":"to die, dead"},
    {"h":"速度","p":"sùdù","e":"speed"},
    {"h":"塑料","p":"sùliào","e":"plastic"},
    {"h":"酸","p":"suān","e":"sour, tart"},
    {"h":"酸奶","p":"suānnǎi","e":"yogurt"},
    {"h":"算","p":"suàn","e":"to calculate"},
    {"h":"随便","p":"suíbiàn","e":"casual, whatever"},
    {"h":"随着","p":"suízhe","e":"along with"},
    {"h":"孙女","p":"sūnnǚ","e":"granddaughter"},
    {"h":"孙子","p":"sūnzi","e":"grandson"},
    {"h":"所有","p":"suǒyǒu","e":"all, every"},
    {"h":"台","p":"tái","e":"measure word for machines"},
    {"h":"抬","p":"tái","e":"to lift, to raise"},
    {"h":"抬头","p":"táitóu","e":"to raise one's head"},
    {"h":"态度","p":"tàidù","e":"attitude, manner"},
    {"h":"弹","p":"tán","e":"to play, to spring"},
    {"h":"谈","p":"tán","e":"to talk, to discuss"},
    {"h":"汤","p":"tāng","e":"soup"},
    {"h":"躺","p":"tǎng","e":"to lie down"},
    {"h":"趟","p":"tàng","e":"measure word for trips"},
    {"h":"讨论","p":"tǎolùn","e":"to discuss"},
    {"h":"讨厌","p":"tǎoyàn","e":"disgusting, to dislike"},
    {"h":"特点","p":"tèdiǎn","e":"characteristic"},
    {"h":"提","p":"tí","e":"to carry, to mention"},
    {"h":"提出","p":"tíchū","e":"to put forward"},
    {"h":"提到","p":"tídào","e":"to mention"},
    {"h":"提供","p":"tígōng","e":"to provide"},
    {"h":"提前","p":"tíqián","e":"ahead of time"},
    {"h":"提醒","p":"tíxǐng","e":"to remind"},
    {"h":"体检","p":"tǐjiǎn","e":"physical examination"},
    {"h":"体温","p":"tǐwēn","e":"body temperature"},
    {"h":"体重","p":"tǐzhòng","e":"body weight"},
    {"h":"填写","p":"tiánxiě","e":"to fill in"},
    {"h":"条件","p":"tiáojiàn","e":"condition"},
    {"h":"听力","p":"tīnglì","e":"listening ability"},
    {"h":"听众","p":"tīngzhòng","e":"audience"},
    {"h":"停","p":"tíng","e":"to stop, to halt"},
    {"h":"停车","p":"tíngchē","e":"to park"},
    {"h":"停车场","p":"tíngchēchǎng","e":"parking lot"},
    {"h":"停止","p":"tíngzhǐ","e":"to stop, to cease"},
    {"h":"通","p":"tōng","e":"to go through"},
    {"h":"通过","p":"tōngguò","e":"to pass through"},
    {"h":"通知","p":"tōngzhī","e":"to notify, notice"},
    {"h":"童年","p":"tóngnián","e":"childhood"},
    {"h":"同时","p":"tóngshí","e":"at the same time"},
    {"h":"同样","p":"tóngyàng","e":"same, similar"},
    {"h":"桶","p":"tǒng","e":"bucket, barrel"},
    {"h":"痛","p":"tòng","e":"painful, sore"},
    {"h":"头痛","p":"tóutòng","e":"headache"},
    {"h":"图","p":"tú","e":"picture, diagram"},
    {"h":"图片","p":"túpiàn","e":"picture, image"},
    {"h":"土","p":"tǔ","e":"earth, soil"},
    {"h":"推","p":"tuī","e":"to push"},
    {"h":"推迟","p":"tuīchí","e":"to postpone"},
    {"h":"推出","p":"tuīchū","e":"to launch"},
    {"h":"脱","p":"tuō","e":"to take off"},
    {"h":"袜子","p":"wàzi","e":"socks"},
    {"h":"外出","p":"wàichū","e":"to go out"},
    {"h":"外套","p":"wàitào","e":"coat, jacket"},
    {"h":"完全","p":"wánquán","e":"complete, completely"},
    {"h":"晚安","p":"wǎn'ān","e":"good night"},
    {"h":"晚餐","p":"wǎncān","e":"dinner, supper"},
    {"h":"网购","p":"wǎnggòu","e":"to shop online"},
    {"h":"往往","p":"wǎngwǎng","e":"often, frequently"},
    {"h":"网页","p":"wǎngyè","e":"webpage"},
    {"h":"网友","p":"wǎngyǒu","e":"netizen"},
    {"h":"网址","p":"wǎngzhǐ","e":"website URL"},
    {"h":"危险","p":"wēixiǎn","e":"dangerous, danger"},
    {"h":"为","p":"wéi","e":"to do, to act"},
    {"h":"味","p":"wèi","e":"taste, flavor"},
    {"h":"味道","p":"wèidào","e":"taste, flavor"},
    {"h":"卫生","p":"wèishēng","e":"hygiene, clean"},
    {"h":"温度","p":"wēndù","e":"temperature"},
    {"h":"闻","p":"wén","e":"to smell, to sniff"},
    {"h":"文件","p":"wénjiàn","e":"document, file"},
    {"h":"文章","p":"wénzhāng","e":"essay, article"},
    {"h":"文字","p":"wénzì","e":"writing, character"},
    {"h":"污染","p":"wūrǎn","e":"contaminated"},
    {"h":"无","p":"wú","e":"to lack, not have"},
    {"h":"无法","p":"wúfǎ","e":"unable, incapable"},
    {"h":"无聊","p":"wúliáo","e":"boring, dull"},
    {"h":"无论","p":"wúlùn","e":"no matter what"},
    {"h":"午餐","p":"wǔcān","e":"lunch"},
    {"h":"误会","p":"wùhuì","e":"to misunderstand"},
    {"h":"吸","p":"xī","e":"to suck, to inhale"},
    {"h":"西部","p":"xībù","e":"western region"},
    {"h":"西红柿","p":"xīhóngshì","e":"tomato"},
    {"h":"吸引","p":"xīyǐn","e":"to attract"},
    {"h":"细","p":"xì","e":"thin, fine, detailed"},
    {"h":"细心","p":"xìxīn","e":"careful, attentive"},
    {"h":"下降","p":"xiàjiàng","e":"to decline, to drop"},
    {"h":"鲜","p":"xiān","e":"fresh"},
    {"h":"鲜花","p":"xiānhuā","e":"fresh flower"},
    {"h":"咸","p":"xián","e":"salty"},
    {"h":"现金","p":"xiànjīn","e":"cash"},
    {"h":"羡慕","p":"xiànmù","e":"to envy, to admire"},
    {"h":"线上","p":"xiànshàng","e":"online"},
    {"h":"线下","p":"xiànxià","e":"offline"},
    {"h":"现有","p":"xiànyǒu","e":"existing, currently available"},
    {"h":"香","p":"xiāng","e":"fragrant"},
    {"h":"相比","p":"xiāngbǐ","e":"to compare with"},
    {"h":"相反","p":"xiāngfǎn","e":"opposite, contrary"},
    {"h":"相互","p":"xiānghù","e":"mutual, each other"},
    {"h":"相同","p":"xiāngtóng","e":"same, identical"},
    {"h":"详细","p":"xiángxì","e":"detailed, thorough"},
    {"h":"响","p":"xiǎng","e":"to make a sound, loud"},
    {"h":"想法","p":"xiǎngfǎ","e":"thought, idea"},
    {"h":"项","p":"xiàng","e":"measure word for items"},
    {"h":"消息","p":"xiāoxi","e":"news, message"},
    {"h":"小吃","p":"xiǎochī","e":"snack, light meal"},
    {"h":"小伙子","p":"xiǎohuǒzi","e":"young man, lad"},
    {"h":"小说","p":"xiǎoshuō","e":"novel, fiction"},
    {"h":"小组","p":"xiǎozǔ","e":"small group, team"},
    {"h":"效果","p":"xiàoguǒ","e":"effect, result"},
    {"h":"笑话","p":"xiàohua","e":"joke"},
    {"h":"血","p":"xiě","e":"blood"},
    {"h":"心","p":"xīn","e":"heart"},
    {"h":"辛苦","p":"xīnkǔ","e":"hard, laborious"},
    {"h":"心情","p":"xīnqíng","e":"mood, feeling"},
    {"h":"信号","p":"xìnhào","e":"signal"},
    {"h":"信息","p":"xìnxī","e":"information"},
    {"h":"信心","p":"xìnxīn","e":"confidence, faith"},
    {"h":"兴奋","p":"xīngfèn","e":"excited, thrilled"},
    {"h":"星星","p":"xīngxing","e":"star"},
    {"h":"醒","p":"xǐng","e":"to wake up"},
    {"h":"性","p":"xìng","e":"nature, character"},
    {"h":"性别","p":"xìngbié","e":"gender, sex"},
    {"h":"幸福","p":"xìngfú","e":"happiness, happy"},
    {"h":"性格","p":"xìnggé","e":"character"},
    {"h":"兄弟","p":"xiōngdì","e":"brothers"},
    {"h":"熊","p":"xióng","e":"bear"},
    {"h":"修","p":"xiū","e":"to repair, to fix"},
    {"h":"修理","p":"xiūlǐ","e":"to repair, to fix"},
    {"h":"许多","p":"xǔduō","e":"many, numerous"},
    {"h":"学费","p":"xuéfèi","e":"tuition fee"},
    {"h":"学院","p":"xuéyuàn","e":"college, academy"},
    {"h":"压","p":"yā","e":"to press, to push down"},
    {"h":"压力","p":"yālì","e":"pressure, stress"},
    {"h":"牙膏","p":"yágāo","e":"toothpaste"},
    {"h":"亚洲","p":"Yàzhōu","e":"Asia"},
    {"h":"烟","p":"yān","e":"cigarette, smoke"},
    {"h":"盐","p":"yán","e":"salt"},
    {"h":"严格","p":"yángé","e":"strict, stringent"},
    {"h":"研究","p":"yánjiū","e":"to research, to study"},
    {"h":"研究生","p":"yánjiūshēng","e":"graduate student"},
    {"h":"严重","p":"yánzhòng","e":"serious, severe"},
    {"h":"演","p":"yǎn","e":"to act, to perform"},
    {"h":"演唱","p":"yǎnchàng","e":"to sing, to perform"},
    {"h":"演出","p":"yǎnchū","e":"to perform"},
    {"h":"眼镜","p":"yǎnjìng","e":"eyeglasses"},
    {"h":"眼前","p":"yǎnqián","e":"before one's eyes"},
    {"h":"演员","p":"yǎnyuán","e":"actor, performer"},
    {"h":"阳光","p":"yángguāng","e":"sunlight, sunshine"},
    {"h":"养成","p":"yǎngchéng","e":"to develop, to cultivate"},
    {"h":"样子","p":"yàngzi","e":"appearance, look"},
    {"h":"邀请","p":"yāoqǐng","e":"to invite"},
    {"h":"要是","p":"yàoshi","e":"if, suppose"},
    {"h":"钥匙","p":"yàoshi","e":"key"},
    {"h":"也许","p":"yěxǔ","e":"maybe, perhaps"},
    {"h":"夜","p":"yè","e":"night"},
    {"h":"夜晚","p":"yèwǎn","e":"night, evening"},
    {"h":"叶子","p":"yèzi","e":"leaf"},
    {"h":"一切","p":"yíqiè","e":"everything"},
    {"h":"已","p":"yǐ","e":"already"},
    {"h":"以内","p":"yǐnèi","e":"within"},
    {"h":"意见","p":"yìjiàn","e":"opinion"},
    {"h":"一生","p":"yìshēng","e":"lifetime"},
    {"h":"艺术","p":"yìshù","e":"art"},
    {"h":"因此","p":"yīncǐ","e":"therefore"},
    {"h":"引起","p":"yǐnqǐ","e":"to cause"},
    {"h":"印象","p":"yìnxiàng","e":"impression"},
    {"h":"赢","p":"yíng","e":"to win"},
    {"h":"赢得","p":"yíngdé","e":"to gain, to win"},
    {"h":"应聘","p":"yìngpìn","e":"to apply for a job"},
    {"h":"勇敢","p":"yǒnggǎn","e":"brave, courageous"},
    {"h":"永远","p":"yǒngyuǎn","e":"forever, always"},
    {"h":"用来","p":"yònglái","e":"to be used for"},
    {"h":"用于","p":"yòngyú","e":"to be used for"},
    {"h":"优点","p":"yōudiǎn","e":"advantage, merit"},
    {"h":"幽默","p":"yōumò","e":"humorous"},
    {"h":"优秀","p":"yōuxiù","e":"excellent, outstanding"},
    {"h":"由","p":"yóu","e":"by, through, from"},
    {"h":"油","p":"yóu","e":"oil, fat, grease"},
    {"h":"尤其","p":"yóuqí","e":"especially"},
    {"h":"游玩","p":"yóuwán","e":"to play, to have fun"},
    {"h":"由于","p":"yóuyú","e":"because of, due to"},
    {"h":"友好","p":"yǒuhǎo","e":"friendly"},
    {"h":"友情","p":"yǒuqíng","e":"friendship"},
    {"h":"有趣","p":"yǒuqù","e":"interesting, fun"},
    {"h":"有效","p":"yǒuxiào","e":"effective"},
    {"h":"友谊","p":"yǒuyì","e":"friendship"},
    {"h":"有着","p":"yǒuzhe","e":"to have, to possess"},
    {"h":"愉快","p":"yúkuài","e":"pleasant, cheerful"},
    {"h":"于是","p":"yúshì","e":"therefore, hence"},
    {"h":"与","p":"yǔ","e":"with, and"},
    {"h":"语法","p":"yǔfǎ","e":"grammar"},
    {"h":"预习","p":"yùxí","e":"to preview, to prepare"},
    {"h":"原来","p":"yuánlái","e":"original, originally"},
    {"h":"原谅","p":"yuánliàng","e":"to forgive"},
    {"h":"原因","p":"yuányīn","e":"cause, reason"},
    {"h":"远离","p":"yuǎnlí","e":"to stay away from"},
    {"h":"院长","p":"yuànzhǎng","e":"dean"},
    {"h":"院子","p":"yuànzi","e":"courtyard, yard"},
    {"h":"约","p":"yuē","e":"to make an appointment"},
    {"h":"约会","p":"yuēhuì","e":"to date, date"},
    {"h":"月饼","p":"yuèbing","e":"mooncake"},
    {"h":"阅读","p":"yuèdú","e":"to read"},
    {"h":"月份","p":"yuèfèn","e":"month"},
    {"h":"云","p":"yún","e":"cloud"},
    {"h":"允许","p":"yǔnxǔ","e":"to permit, to allow"},
    {"h":"杂志","p":"zázhì","e":"magazine"},
    {"h":"再次","p":"zàicì","e":"once again"},
    {"h":"再说","p":"zàishuō","e":"to postpone, besides"},
    {"h":"暂时","p":"zànshí","e":"temporary"},
    {"h":"暂停","p":"zàntíng","e":"to suspend, to pause"},
    {"h":"早餐","p":"zǎocān","e":"breakfast"},
    {"h":"早晨","p":"zǎochen","e":"morning"},
    {"h":"责任","p":"zérèn","e":"responsibility, duty"},
    {"h":"增加","p":"zēngjiā","e":"to increase, to add"},
    {"h":"增长","p":"zēngzhǎng","e":"to increase, to grow"},
    {"h":"招聘","p":"zhāopìn","e":"to recruit, to hire"},
    {"h":"着","p":"zháo","e":"to touch, to catch"},
    {"h":"着火","p":"zháohuǒ","e":"to catch fire"},
    {"h":"者","p":"zhě","e":"suffix meaning person"},
    {"h":"真正","p":"zhēnzhèng","e":"true, genuine"},
    {"h":"整","p":"zhěng","e":"whole, complete"},
    {"h":"整个","p":"zhěnggè","e":"whole, entire"},
    {"h":"整理","p":"zhěnglǐ","e":"to arrange, to tidy up"},
    {"h":"证","p":"zhèng","e":"certificate, proof"},
    {"h":"正常","p":"zhèngcháng","e":"normal, regular"},
    {"h":"正好","p":"zhènghǎo","e":"exactly right"},
    {"h":"证件","p":"zhèngjiàn","e":"ID card, credentials"},
    {"h":"证明","p":"zhèngmíng","e":"to prove, proof"},
    {"h":"正确","p":"zhèngquè","e":"correct, right"},
    {"h":"正式","p":"zhèngshì","e":"formal, official"},
    {"h":"之","p":"zhī","e":"auxiliary word"},
    {"h":"支持","p":"zhīchí","e":"to support, to back"},
    {"h":"支付","p":"zhīfù","e":"to pay"},
    {"h":"之后","p":"zhīhòu","e":"after, later"},
    {"h":"之间","p":"zhījiān","e":"between, among"},
    {"h":"之前","p":"zhīqián","e":"before, prior to"},
    {"h":"知识","p":"zhīshi","e":"knowledge"},
    {"h":"之中","p":"zhīzhōng","e":"among, inside"},
    {"h":"值","p":"zhí","e":"to be worth"},
    {"h":"值得","p":"zhídé","e":"to be worth"},
    {"h":"直接","p":"zhíjiē","e":"direct"},
    {"h":"植物","p":"zhíwù","e":"plant, vegetation"},
    {"h":"职业","p":"zhíyè","e":"occupation, profession"},
    {"h":"指","p":"zhǐ","e":"to point to"},
    {"h":"指出","p":"zhǐchū","e":"to point out"},
    {"h":"只好","p":"zhǐhǎo","e":"have to"},
    {"h":"纸巾","p":"zhǐjīn","e":"tissue paper"},
    {"h":"质量","p":"zhìliàng","e":"quality"},
    {"h":"至少","p":"zhìshǎo","e":"at least"},
    {"h":"中餐","p":"zhōngcān","e":"Chinese food"},
    {"h":"中年","p":"zhōngnián","e":"middle age"},
    {"h":"种","p":"zhòng","e":"to plant, to grow"},
    {"h":"重","p":"zhòng","e":"heavy, important"},
    {"h":"重点","p":"zhòngdiǎn","e":"key point, emphasis"},
    {"h":"重视","p":"zhòngshì","e":"to pay attention to"},
    {"h":"周围","p":"zhōuwéi","e":"around, surrounding"},
    {"h":"主意","p":"zhǔyi","e":"idea, plan"},
    {"h":"祝","p":"zhù","e":"to wish"},
    {"h":"祝贺","p":"zhùhè","e":"to congratulate"},
    {"h":"著名","p":"zhùmíng","e":"famous, well-known"},
    {"h":"专门","p":"zhuānmén","e":"specially"},
    {"h":"专业","p":"zhuānyè","e":"specialty, major"},
    {"h":"转","p":"zhuǎn","e":"to turn, to transfer"},
    {"h":"转发","p":"zhuǎnfā","e":"to forward"},
    {"h":"转机","p":"zhuǎnjī","e":"to transfer flight"},
    {"h":"赚","p":"zhuàn","e":"to earn"},
    {"h":"装","p":"zhuāng","e":"to load, to install"},
    {"h":"准","p":"zhǔn","e":"accurate, exact"},
    {"h":"准确","p":"zhǔnquè","e":"accurate, precise"},
    {"h":"准时","p":"zhǔnshí","e":"on time, punctual"},
    {"h":"资料","p":"zīliào","e":"materials, data"},
    {"h":"仔细","p":"zǐxì","e":"careful, attentive"},
    {"h":"自","p":"zì","e":"from, since, oneself"},
    {"h":"自然","p":"zìrán","e":"nature, natural"},
    {"h":"自习","p":"zìxí","e":"to study on one's own"},
    {"h":"自信","p":"zìxìn","e":"self-confidence"},
    {"h":"自学","p":"zìxué","e":"to teach oneself"},
    {"h":"总结","p":"zǒngjié","e":"to summarize, summary"},
    {"h":"租","p":"zū","e":"to rent, to hire"},
    {"h":"组","p":"zǔ","e":"group, team"},
    {"h":"最终","p":"zuìzhōng","e":"final, ultimate"},
    {"h":"尊重","p":"zūnzhòng","e":"to respect"},
    {"h":"左右","p":"zuǒyòu","e":"about, around"},
    {"h":"座","p":"zuò","e":"seat, measure word"},
    {"h":"做法","p":"zuòfǎ","e":"way of doing things"},
    {"h":"作家","p":"zuòjiā","e":"writer, author"},
    {"h":"做梦","p":"zuòmèng","e":"to dream"},
    {"h":"作品","p":"zuòpǐn","e":"work, creation"},
    {"h":"作为","p":"zuòwéi","e":"to act as, as"},
    {"h":"座位","p":"zuòwèi","e":"seat"},
    {"h":"作文","p":"zuòwén","e":"composition"},
    {"h":"作用","p":"zuòyòng","e":"function, role"},
    {"h":"作者","p":"zuòzhě","e":"author, writer"}
  ]
};

// Level info for UI
const HSK_LEVELS = {
  elementary: [1, 2, 3],
  intermediate: [4, 5, 6],
  advanced: [7, 8, 9]
};

const HSK_INFO = {
  1: { name: "HSK 1", words: 300, tier: "elementary" },
  2: { name: "HSK 2", words: 300, tier: "elementary" },
  3: { name: "HSK 3", words: 600, tier: "elementary" },
  4: { name: "HSK 4", words: 1000, tier: "intermediate" },
  5: { name: "HSK 5", words: 2500, tier: "intermediate" },
  6: { name: "HSK 6", words: 5000, tier: "intermediate" },
  7: { name: "HSK 7-9", words: 11000, tier: "advanced" }
};
